// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$742 {

    static final FunctionDescriptor I_RpcPauseExecution$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle I_RpcPauseExecution$MH = RuntimeHelper.downcallHandle(
        "I_RpcPauseExecution",
        constants$742.I_RpcPauseExecution$FUNC
    );
    static final FunctionDescriptor I_RpcGetExtendedError$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle I_RpcGetExtendedError$MH = RuntimeHelper.downcallHandle(
        "I_RpcGetExtendedError",
        constants$742.I_RpcGetExtendedError$FUNC
    );
    static final FunctionDescriptor I_RpcSystemHandleTypeSpecificWork$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle I_RpcSystemHandleTypeSpecificWork$MH = RuntimeHelper.downcallHandle(
        "I_RpcSystemHandleTypeSpecificWork",
        constants$742.I_RpcSystemHandleTypeSpecificWork$FUNC
    );
    static final FunctionDescriptor PRPC_RUNDOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PRPC_RUNDOWN$MH = RuntimeHelper.downcallHandle(
        constants$742.PRPC_RUNDOWN$FUNC
    );
    static final FunctionDescriptor I_RpcMonitorAssociation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcMonitorAssociation$MH = RuntimeHelper.downcallHandle(
        "I_RpcMonitorAssociation",
        constants$742.I_RpcMonitorAssociation$FUNC
    );
}


