// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$361 {

    static final FunctionDescriptor DefineDosDeviceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DefineDosDeviceA$MH = RuntimeHelper.downcallHandle(
        "DefineDosDeviceA",
        constants$361.DefineDosDeviceA$FUNC
    );
    static final FunctionDescriptor QueryDosDeviceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle QueryDosDeviceA$MH = RuntimeHelper.downcallHandle(
        "QueryDosDeviceA",
        constants$361.QueryDosDeviceA$FUNC
    );
    static final FunctionDescriptor CreateFileTransactedA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateFileTransactedA$MH = RuntimeHelper.downcallHandle(
        "CreateFileTransactedA",
        constants$361.CreateFileTransactedA$FUNC
    );
    static final FunctionDescriptor CreateFileTransactedW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateFileTransactedW$MH = RuntimeHelper.downcallHandle(
        "CreateFileTransactedW",
        constants$361.CreateFileTransactedW$FUNC
    );
    static final FunctionDescriptor ReOpenFile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ReOpenFile$MH = RuntimeHelper.downcallHandle(
        "ReOpenFile",
        constants$361.ReOpenFile$FUNC
    );
    static final FunctionDescriptor SetFileAttributesTransactedA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetFileAttributesTransactedA$MH = RuntimeHelper.downcallHandle(
        "SetFileAttributesTransactedA",
        constants$361.SetFileAttributesTransactedA$FUNC
    );
}


