// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$571 {

    static final FunctionDescriptor SetSystemCursor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetSystemCursor$MH = RuntimeHelper.downcallHandle(
        "SetSystemCursor",
        constants$571.SetSystemCursor$FUNC
    );
    static final FunctionDescriptor LoadIconA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LoadIconA$MH = RuntimeHelper.downcallHandle(
        "LoadIconA",
        constants$571.LoadIconA$FUNC
    );
    static final FunctionDescriptor LoadIconW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LoadIconW$MH = RuntimeHelper.downcallHandle(
        "LoadIconW",
        constants$571.LoadIconW$FUNC
    );
    static final FunctionDescriptor PrivateExtractIconsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PrivateExtractIconsA$MH = RuntimeHelper.downcallHandle(
        "PrivateExtractIconsA",
        constants$571.PrivateExtractIconsA$FUNC
    );
    static final FunctionDescriptor PrivateExtractIconsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle PrivateExtractIconsW$MH = RuntimeHelper.downcallHandle(
        "PrivateExtractIconsW",
        constants$571.PrivateExtractIconsW$FUNC
    );
    static final FunctionDescriptor CreateIcon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateIcon$MH = RuntimeHelper.downcallHandle(
        "CreateIcon",
        constants$571.CreateIcon$FUNC
    );
}


