// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1064 {

    static final FunctionDescriptor DllCanUnloadNow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle DllCanUnloadNow$MH = RuntimeHelper.downcallHandle(
        "DllCanUnloadNow",
        constants$1064.DllCanUnloadNow$FUNC
    );
    static final FunctionDescriptor CoTaskMemAlloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle CoTaskMemAlloc$MH = RuntimeHelper.downcallHandle(
        "CoTaskMemAlloc",
        constants$1064.CoTaskMemAlloc$FUNC
    );
    static final FunctionDescriptor CoTaskMemRealloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle CoTaskMemRealloc$MH = RuntimeHelper.downcallHandle(
        "CoTaskMemRealloc",
        constants$1064.CoTaskMemRealloc$FUNC
    );
    static final FunctionDescriptor CoTaskMemFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoTaskMemFree$MH = RuntimeHelper.downcallHandle(
        "CoTaskMemFree",
        constants$1064.CoTaskMemFree$FUNC
    );
    static final FunctionDescriptor CoFileTimeNow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoFileTimeNow$MH = RuntimeHelper.downcallHandle(
        "CoFileTimeNow",
        constants$1064.CoFileTimeNow$FUNC
    );
    static final FunctionDescriptor CLSIDFromProgIDEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLSIDFromProgIDEx$MH = RuntimeHelper.downcallHandle(
        "CLSIDFromProgIDEx",
        constants$1064.CLSIDFromProgIDEx$FUNC
    );
}


