// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$904 {

    static final FunctionDescriptor NdrConvert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConvert$MH = RuntimeHelper.downcallHandle(
        "NdrConvert",
        constants$904.NdrConvert$FUNC
    );
    static final FunctionDescriptor NdrUserMarshalSimpleTypeConvert$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrUserMarshalSimpleTypeConvert$MH = RuntimeHelper.downcallHandle(
        "NdrUserMarshalSimpleTypeConvert",
        constants$904.NdrUserMarshalSimpleTypeConvert$FUNC
    );
    static final FunctionDescriptor NdrClientInitializeNew$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NdrClientInitializeNew$MH = RuntimeHelper.downcallHandle(
        "NdrClientInitializeNew",
        constants$904.NdrClientInitializeNew$FUNC
    );
    static final FunctionDescriptor NdrServerInitializeNew$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrServerInitializeNew$MH = RuntimeHelper.downcallHandle(
        "NdrServerInitializeNew",
        constants$904.NdrServerInitializeNew$FUNC
    );
    static final FunctionDescriptor NdrServerInitializePartial$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NdrServerInitializePartial$MH = RuntimeHelper.downcallHandle(
        "NdrServerInitializePartial",
        constants$904.NdrServerInitializePartial$FUNC
    );
    static final FunctionDescriptor NdrClientInitialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NdrClientInitialize$MH = RuntimeHelper.downcallHandle(
        "NdrClientInitialize",
        constants$904.NdrClientInitialize$FUNC
    );
}


