// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1245 {

    static final FunctionDescriptor SafeArrayGetElement$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArrayGetElement$MH = RuntimeHelper.downcallHandle(
        "SafeArrayGetElement",
        constants$1245.SafeArrayGetElement$FUNC
    );
    static final FunctionDescriptor SafeArrayPutElement$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArrayPutElement$MH = RuntimeHelper.downcallHandle(
        "SafeArrayPutElement",
        constants$1245.SafeArrayPutElement$FUNC
    );
    static final FunctionDescriptor SafeArrayCopy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArrayCopy$MH = RuntimeHelper.downcallHandle(
        "SafeArrayCopy",
        constants$1245.SafeArrayCopy$FUNC
    );
    static final FunctionDescriptor SafeArrayPtrOfIndex$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArrayPtrOfIndex$MH = RuntimeHelper.downcallHandle(
        "SafeArrayPtrOfIndex",
        constants$1245.SafeArrayPtrOfIndex$FUNC
    );
    static final FunctionDescriptor SafeArraySetRecordInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArraySetRecordInfo$MH = RuntimeHelper.downcallHandle(
        "SafeArraySetRecordInfo",
        constants$1245.SafeArraySetRecordInfo$FUNC
    );
    static final FunctionDescriptor SafeArrayGetRecordInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SafeArrayGetRecordInfo$MH = RuntimeHelper.downcallHandle(
        "SafeArrayGetRecordInfo",
        constants$1245.SafeArrayGetRecordInfo$FUNC
    );
}


