// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$954 {

    static final FunctionDescriptor EnumPrintProcessorsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EnumPrintProcessorsW$MH = RuntimeHelper.downcallHandle(
        "EnumPrintProcessorsW",
        constants$954.EnumPrintProcessorsW$FUNC
    );
    static final FunctionDescriptor GetPrintProcessorDirectoryA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPrintProcessorDirectoryA$MH = RuntimeHelper.downcallHandle(
        "GetPrintProcessorDirectoryA",
        constants$954.GetPrintProcessorDirectoryA$FUNC
    );
    static final FunctionDescriptor GetPrintProcessorDirectoryW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPrintProcessorDirectoryW$MH = RuntimeHelper.downcallHandle(
        "GetPrintProcessorDirectoryW",
        constants$954.GetPrintProcessorDirectoryW$FUNC
    );
    static final FunctionDescriptor EnumPrintProcessorDatatypesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EnumPrintProcessorDatatypesA$MH = RuntimeHelper.downcallHandle(
        "EnumPrintProcessorDatatypesA",
        constants$954.EnumPrintProcessorDatatypesA$FUNC
    );
    static final FunctionDescriptor EnumPrintProcessorDatatypesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EnumPrintProcessorDatatypesW$MH = RuntimeHelper.downcallHandle(
        "EnumPrintProcessorDatatypesW",
        constants$954.EnumPrintProcessorDatatypesW$FUNC
    );
    static final FunctionDescriptor DeletePrintProcessorA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeletePrintProcessorA$MH = RuntimeHelper.downcallHandle(
        "DeletePrintProcessorA",
        constants$954.DeletePrintProcessorA$FUNC
    );
}


