// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$245 {

    static final FunctionDescriptor TlsFree$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle TlsFree$MH = RuntimeHelper.downcallHandle(
        "TlsFree",
        constants$245.TlsFree$FUNC
    );
    static final FunctionDescriptor CreateProcessA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateProcessA$MH = RuntimeHelper.downcallHandle(
        "CreateProcessA",
        constants$245.CreateProcessA$FUNC
    );
    static final FunctionDescriptor CreateProcessW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateProcessW$MH = RuntimeHelper.downcallHandle(
        "CreateProcessW",
        constants$245.CreateProcessW$FUNC
    );
    static final FunctionDescriptor SetProcessShutdownParameters$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetProcessShutdownParameters$MH = RuntimeHelper.downcallHandle(
        "SetProcessShutdownParameters",
        constants$245.SetProcessShutdownParameters$FUNC
    );
    static final FunctionDescriptor GetProcessVersion$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetProcessVersion$MH = RuntimeHelper.downcallHandle(
        "GetProcessVersion",
        constants$245.GetProcessVersion$FUNC
    );
    static final FunctionDescriptor GetStartupInfoW$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetStartupInfoW$MH = RuntimeHelper.downcallHandle(
        "GetStartupInfoW",
        constants$245.GetStartupInfoW$FUNC
    );
}


