// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$699 {

    static final FunctionDescriptor midiOutGetDevCapsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle midiOutGetDevCapsW$MH = RuntimeHelper.downcallHandle(
        "midiOutGetDevCapsW",
        constants$699.midiOutGetDevCapsW$FUNC
    );
    static final FunctionDescriptor midiOutGetVolume$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle midiOutGetVolume$MH = RuntimeHelper.downcallHandle(
        "midiOutGetVolume",
        constants$699.midiOutGetVolume$FUNC
    );
    static final FunctionDescriptor midiOutSetVolume$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle midiOutSetVolume$MH = RuntimeHelper.downcallHandle(
        "midiOutSetVolume",
        constants$699.midiOutSetVolume$FUNC
    );
    static final FunctionDescriptor midiOutGetErrorTextA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle midiOutGetErrorTextA$MH = RuntimeHelper.downcallHandle(
        "midiOutGetErrorTextA",
        constants$699.midiOutGetErrorTextA$FUNC
    );
    static final FunctionDescriptor midiOutGetErrorTextW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle midiOutGetErrorTextW$MH = RuntimeHelper.downcallHandle(
        "midiOutGetErrorTextW",
        constants$699.midiOutGetErrorTextW$FUNC
    );
    static final FunctionDescriptor midiOutOpen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle midiOutOpen$MH = RuntimeHelper.downcallHandle(
        "midiOutOpen",
        constants$699.midiOutOpen$FUNC
    );
}


