// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1157 {

    static final FunctionDescriptor CoRegisterMessageFilter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoRegisterMessageFilter$MH = RuntimeHelper.downcallHandle(
        "CoRegisterMessageFilter",
        constants$1157.CoRegisterMessageFilter$FUNC
    );
    static final FunctionDescriptor CoRegisterChannelHook$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoRegisterChannelHook$MH = RuntimeHelper.downcallHandle(
        "CoRegisterChannelHook",
        constants$1157.CoRegisterChannelHook$FUNC
    );
    static final FunctionDescriptor CoTreatAsClass$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoTreatAsClass$MH = RuntimeHelper.downcallHandle(
        "CoTreatAsClass",
        constants$1157.CoTreatAsClass$FUNC
    );
    static final FunctionDescriptor CreateDataAdviseHolder$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateDataAdviseHolder$MH = RuntimeHelper.downcallHandle(
        "CreateDataAdviseHolder",
        constants$1157.CreateDataAdviseHolder$FUNC
    );
    static final FunctionDescriptor CreateDataCache$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateDataCache$MH = RuntimeHelper.downcallHandle(
        "CreateDataCache",
        constants$1157.CreateDataCache$FUNC
    );
    static final FunctionDescriptor StgOpenAsyncDocfileOnIFillLockBytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle StgOpenAsyncDocfileOnIFillLockBytes$MH = RuntimeHelper.downcallHandle(
        "StgOpenAsyncDocfileOnIFillLockBytes",
        constants$1157.StgOpenAsyncDocfileOnIFillLockBytes$FUNC
    );
}


