// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$694 {

    static final FunctionDescriptor waveInGetDevCapsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle waveInGetDevCapsW$MH = RuntimeHelper.downcallHandle(
        "waveInGetDevCapsW",
        constants$694.waveInGetDevCapsW$FUNC
    );
    static final FunctionDescriptor waveInGetErrorTextA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle waveInGetErrorTextA$MH = RuntimeHelper.downcallHandle(
        "waveInGetErrorTextA",
        constants$694.waveInGetErrorTextA$FUNC
    );
    static final FunctionDescriptor waveInGetErrorTextW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle waveInGetErrorTextW$MH = RuntimeHelper.downcallHandle(
        "waveInGetErrorTextW",
        constants$694.waveInGetErrorTextW$FUNC
    );
    static final FunctionDescriptor waveInOpen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle waveInOpen$MH = RuntimeHelper.downcallHandle(
        "waveInOpen",
        constants$694.waveInOpen$FUNC
    );
    static final FunctionDescriptor waveInClose$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle waveInClose$MH = RuntimeHelper.downcallHandle(
        "waveInClose",
        constants$694.waveInClose$FUNC
    );
    static final FunctionDescriptor waveInPrepareHeader$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle waveInPrepareHeader$MH = RuntimeHelper.downcallHandle(
        "waveInPrepareHeader",
        constants$694.waveInPrepareHeader$FUNC
    );
}


