// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$382 {

    static final FunctionDescriptor GetComputerNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetComputerNameW$MH = RuntimeHelper.downcallHandle(
        "GetComputerNameW",
        constants$382.GetComputerNameW$FUNC
    );
    static final FunctionDescriptor DnsHostnameToComputerNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DnsHostnameToComputerNameA$MH = RuntimeHelper.downcallHandle(
        "DnsHostnameToComputerNameA",
        constants$382.DnsHostnameToComputerNameA$FUNC
    );
    static final FunctionDescriptor DnsHostnameToComputerNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DnsHostnameToComputerNameW$MH = RuntimeHelper.downcallHandle(
        "DnsHostnameToComputerNameW",
        constants$382.DnsHostnameToComputerNameW$FUNC
    );
    static final FunctionDescriptor GetUserNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetUserNameA$MH = RuntimeHelper.downcallHandle(
        "GetUserNameA",
        constants$382.GetUserNameA$FUNC
    );
    static final FunctionDescriptor GetUserNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetUserNameW$MH = RuntimeHelper.downcallHandle(
        "GetUserNameW",
        constants$382.GetUserNameW$FUNC
    );
    static final FunctionDescriptor LogonUserA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LogonUserA$MH = RuntimeHelper.downcallHandle(
        "LogonUserA",
        constants$382.LogonUserA$FUNC
    );
}


