// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1345 {

    static final FunctionDescriptor ImmRegisterWordA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmRegisterWordA$MH = RuntimeHelper.downcallHandle(
        "ImmRegisterWordA",
        constants$1345.ImmRegisterWordA$FUNC
    );
    static final FunctionDescriptor ImmRegisterWordW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmRegisterWordW$MH = RuntimeHelper.downcallHandle(
        "ImmRegisterWordW",
        constants$1345.ImmRegisterWordW$FUNC
    );
    static final FunctionDescriptor ImmUnregisterWordA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmUnregisterWordA$MH = RuntimeHelper.downcallHandle(
        "ImmUnregisterWordA",
        constants$1345.ImmUnregisterWordA$FUNC
    );
    static final FunctionDescriptor ImmUnregisterWordW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmUnregisterWordW$MH = RuntimeHelper.downcallHandle(
        "ImmUnregisterWordW",
        constants$1345.ImmUnregisterWordW$FUNC
    );
    static final FunctionDescriptor ImmGetRegisterWordStyleA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetRegisterWordStyleA$MH = RuntimeHelper.downcallHandle(
        "ImmGetRegisterWordStyleA",
        constants$1345.ImmGetRegisterWordStyleA$FUNC
    );
    static final FunctionDescriptor ImmGetRegisterWordStyleW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetRegisterWordStyleW$MH = RuntimeHelper.downcallHandle(
        "ImmGetRegisterWordStyleW",
        constants$1345.ImmGetRegisterWordStyleW$FUNC
    );
}


