// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$341 {

    static final FunctionDescriptor lstrcmpW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpW$MH = RuntimeHelper.downcallHandle(
        "lstrcmpW",
        constants$341.lstrcmpW$FUNC
    );
    static final FunctionDescriptor lstrcmpiA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpiA$MH = RuntimeHelper.downcallHandle(
        "lstrcmpiA",
        constants$341.lstrcmpiA$FUNC
    );
    static final FunctionDescriptor lstrcmpiW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpiW$MH = RuntimeHelper.downcallHandle(
        "lstrcmpiW",
        constants$341.lstrcmpiW$FUNC
    );
    static final FunctionDescriptor lstrcpynA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle lstrcpynA$MH = RuntimeHelper.downcallHandle(
        "lstrcpynA",
        constants$341.lstrcpynA$FUNC
    );
    static final FunctionDescriptor lstrcpynW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle lstrcpynW$MH = RuntimeHelper.downcallHandle(
        "lstrcpynW",
        constants$341.lstrcpynW$FUNC
    );
    static final FunctionDescriptor lstrcpyA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcpyA$MH = RuntimeHelper.downcallHandle(
        "lstrcpyA",
        constants$341.lstrcpyA$FUNC
    );
}


