// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$706 {

    static final FunctionDescriptor mixerMessage$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mixerMessage$MH = RuntimeHelper.downcallHandle(
        "mixerMessage",
        constants$706.mixerMessage$FUNC
    );
    static final FunctionDescriptor mixerGetLineInfoA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mixerGetLineInfoA$MH = RuntimeHelper.downcallHandle(
        "mixerGetLineInfoA",
        constants$706.mixerGetLineInfoA$FUNC
    );
    static final FunctionDescriptor mixerGetLineInfoW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mixerGetLineInfoW$MH = RuntimeHelper.downcallHandle(
        "mixerGetLineInfoW",
        constants$706.mixerGetLineInfoW$FUNC
    );
    static final FunctionDescriptor mixerGetID$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mixerGetID$MH = RuntimeHelper.downcallHandle(
        "mixerGetID",
        constants$706.mixerGetID$FUNC
    );
    static final FunctionDescriptor mixerGetLineControlsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mixerGetLineControlsA$MH = RuntimeHelper.downcallHandle(
        "mixerGetLineControlsA",
        constants$706.mixerGetLineControlsA$FUNC
    );
    static final FunctionDescriptor mixerGetLineControlsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mixerGetLineControlsW$MH = RuntimeHelper.downcallHandle(
        "mixerGetLineControlsW",
        constants$706.mixerGetLineControlsW$FUNC
    );
}


