// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$916 {

    static final FunctionDescriptor RpcSmSwapClientAllocFree$OldClientFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcSmSwapClientAllocFree$OldClientFree$MH = RuntimeHelper.downcallHandle(
        constants$916.RpcSmSwapClientAllocFree$OldClientFree$FUNC
    );
    static final FunctionDescriptor RpcSmSwapClientAllocFree$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcSmSwapClientAllocFree$MH = RuntimeHelper.downcallHandle(
        "RpcSmSwapClientAllocFree",
        constants$916.RpcSmSwapClientAllocFree$FUNC
    );
    static final FunctionDescriptor NdrRpcSsEnableAllocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrRpcSsEnableAllocate$MH = RuntimeHelper.downcallHandle(
        "NdrRpcSsEnableAllocate",
        constants$916.NdrRpcSsEnableAllocate$FUNC
    );
    static final FunctionDescriptor NdrRpcSsDisableAllocate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrRpcSsDisableAllocate$MH = RuntimeHelper.downcallHandle(
        "NdrRpcSsDisableAllocate",
        constants$916.NdrRpcSsDisableAllocate$FUNC
    );
    static final FunctionDescriptor NdrRpcSmSetClientToOsf$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrRpcSmSetClientToOsf$MH = RuntimeHelper.downcallHandle(
        "NdrRpcSmSetClientToOsf",
        constants$916.NdrRpcSmSetClientToOsf$FUNC
    );
}


