// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$738 {

    static final FunctionDescriptor RPC_FORWARD_FUNCTION$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_FORWARD_FUNCTION$MH = RuntimeHelper.downcallHandle(
        constants$738.RPC_FORWARD_FUNCTION$FUNC
    );
    static final FunctionDescriptor RPC_ADDRESS_CHANGE_FN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_ADDRESS_CHANGE_FN$MH = RuntimeHelper.downcallHandle(
        constants$738.RPC_ADDRESS_CHANGE_FN$FUNC
    );
    static final FunctionDescriptor RPC_DISPATCH_FUNCTION$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_DISPATCH_FUNCTION$MH = RuntimeHelper.downcallHandle(
        constants$738.RPC_DISPATCH_FUNCTION$FUNC
    );
}


