// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$92 {

    static final FunctionDescriptor _wcserror_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _wcserror_s$MH = RuntimeHelper.downcallHandle(
        "_wcserror_s",
        constants$92._wcserror_s$FUNC
    );
    static final FunctionDescriptor __wcserror$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __wcserror$MH = RuntimeHelper.downcallHandle(
        "__wcserror",
        constants$92.__wcserror$FUNC
    );
    static final FunctionDescriptor __wcserror_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __wcserror_s$MH = RuntimeHelper.downcallHandle(
        "__wcserror_s",
        constants$92.__wcserror_s$FUNC
    );
    static final FunctionDescriptor _wcsicmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsicmp$MH = RuntimeHelper.downcallHandle(
        "_wcsicmp",
        constants$92._wcsicmp$FUNC
    );
    static final FunctionDescriptor _wcsicmp_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsicmp_l$MH = RuntimeHelper.downcallHandle(
        "_wcsicmp_l",
        constants$92._wcsicmp_l$FUNC
    );
    static final FunctionDescriptor _wcsnicmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _wcsnicmp$MH = RuntimeHelper.downcallHandle(
        "_wcsnicmp",
        constants$92._wcsnicmp$FUNC
    );
}


