// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$196 {

    static final FunctionDescriptor SearchPathW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SearchPathW$MH = RuntimeHelper.downcallHandle(
        "SearchPathW",
        constants$196.SearchPathW$FUNC
    );
    static final FunctionDescriptor SearchPathA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SearchPathA$MH = RuntimeHelper.downcallHandle(
        "SearchPathA",
        constants$196.SearchPathA$FUNC
    );
    static final FunctionDescriptor NeedCurrentDirectoryForExePathA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NeedCurrentDirectoryForExePathA$MH = RuntimeHelper.downcallHandle(
        "NeedCurrentDirectoryForExePathA",
        constants$196.NeedCurrentDirectoryForExePathA$FUNC
    );
    static final FunctionDescriptor NeedCurrentDirectoryForExePathW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NeedCurrentDirectoryForExePathW$MH = RuntimeHelper.downcallHandle(
        "NeedCurrentDirectoryForExePathW",
        constants$196.NeedCurrentDirectoryForExePathW$FUNC
    );
    static final FunctionDescriptor CompareFileTime$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CompareFileTime$MH = RuntimeHelper.downcallHandle(
        "CompareFileTime",
        constants$196.CompareFileTime$FUNC
    );
    static final FunctionDescriptor CreateDirectoryA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateDirectoryA$MH = RuntimeHelper.downcallHandle(
        "CreateDirectoryA",
        constants$196.CreateDirectoryA$FUNC
    );
}


