// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$271 {

    static final FunctionDescriptor SetProcessValidCallTargets$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetProcessValidCallTargets$MH = RuntimeHelper.downcallHandle(
        "SetProcessValidCallTargets",
        constants$271.SetProcessValidCallTargets$FUNC
    );
    static final FunctionDescriptor SetProcessValidCallTargetsForMappedView$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SetProcessValidCallTargetsForMappedView$MH = RuntimeHelper.downcallHandle(
        "SetProcessValidCallTargetsForMappedView",
        constants$271.SetProcessValidCallTargetsForMappedView$FUNC
    );
    static final FunctionDescriptor VirtualAllocFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle VirtualAllocFromApp$MH = RuntimeHelper.downcallHandle(
        "VirtualAllocFromApp",
        constants$271.VirtualAllocFromApp$FUNC
    );
    static final FunctionDescriptor VirtualProtectFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VirtualProtectFromApp$MH = RuntimeHelper.downcallHandle(
        "VirtualProtectFromApp",
        constants$271.VirtualProtectFromApp$FUNC
    );
    static final FunctionDescriptor OpenFileMappingFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenFileMappingFromApp$MH = RuntimeHelper.downcallHandle(
        "OpenFileMappingFromApp",
        constants$271.OpenFileMappingFromApp$FUNC
    );
    static final FunctionDescriptor QueryVirtualMemoryInformation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryVirtualMemoryInformation$MH = RuntimeHelper.downcallHandle(
        "QueryVirtualMemoryInformation",
        constants$271.QueryVirtualMemoryInformation$FUNC
    );
}


