// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$891 {

    static final FunctionDescriptor NdrConformantVaryingStructUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrConformantVaryingStructUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrConformantVaryingStructUnmarshall",
        constants$891.NdrConformantVaryingStructUnmarshall$FUNC
    );
    static final FunctionDescriptor NdrComplexStructUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrComplexStructUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrComplexStructUnmarshall",
        constants$891.NdrComplexStructUnmarshall$FUNC
    );
    static final FunctionDescriptor NdrFixedArrayUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrFixedArrayUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrFixedArrayUnmarshall",
        constants$891.NdrFixedArrayUnmarshall$FUNC
    );
    static final FunctionDescriptor NdrConformantArrayUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrConformantArrayUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrConformantArrayUnmarshall",
        constants$891.NdrConformantArrayUnmarshall$FUNC
    );
    static final FunctionDescriptor NdrConformantVaryingArrayUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrConformantVaryingArrayUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrConformantVaryingArrayUnmarshall",
        constants$891.NdrConformantVaryingArrayUnmarshall$FUNC
    );
    static final FunctionDescriptor NdrVaryingArrayUnmarshall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle NdrVaryingArrayUnmarshall$MH = RuntimeHelper.downcallHandle(
        "NdrVaryingArrayUnmarshall",
        constants$891.NdrVaryingArrayUnmarshall$FUNC
    );
}


