// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1378 {

    static final FunctionDescriptor InetPtonW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle InetPtonW$MH = RuntimeHelper.downcallHandle(
        "InetPtonW",
        constants$1378.InetPtonW$FUNC
    );
    static final FunctionDescriptor inet_ntop$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle inet_ntop$MH = RuntimeHelper.downcallHandle(
        "inet_ntop",
        constants$1378.inet_ntop$FUNC
    );
    static final FunctionDescriptor InetNtopW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle InetNtopW$MH = RuntimeHelper.downcallHandle(
        "InetNtopW",
        constants$1378.InetNtopW$FUNC
    );
    static final FunctionDescriptor gai_strerrorA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle gai_strerrorA$MH = RuntimeHelper.downcallHandle(
        "gai_strerrorA",
        constants$1378.gai_strerrorA$FUNC
    );
    static final FunctionDescriptor gai_strerrorW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle gai_strerrorW$MH = RuntimeHelper.downcallHandle(
        "gai_strerrorW",
        constants$1378.gai_strerrorW$FUNC
    );
    static final FunctionDescriptor setipv4sourcefilter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        MemoryLayout.structLayout(
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    Constants$root.C_CHAR$LAYOUT.withName("s_b1"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b2"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b3"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b4")
                ).withName("S_un_b"),
                MemoryLayout.structLayout(
                    Constants$root.C_SHORT$LAYOUT.withName("s_w1"),
                    Constants$root.C_SHORT$LAYOUT.withName("s_w2")
                ).withName("S_un_w"),
                Constants$root.C_LONG$LAYOUT.withName("S_addr")
            ).withName("S_un")
        ).withName("in_addr"),
        MemoryLayout.structLayout(
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    Constants$root.C_CHAR$LAYOUT.withName("s_b1"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b2"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b3"),
                    Constants$root.C_CHAR$LAYOUT.withName("s_b4")
                ).withName("S_un_b"),
                MemoryLayout.structLayout(
                    Constants$root.C_SHORT$LAYOUT.withName("s_w1"),
                    Constants$root.C_SHORT$LAYOUT.withName("s_w2")
                ).withName("S_un_w"),
                Constants$root.C_LONG$LAYOUT.withName("S_addr")
            ).withName("S_un")
        ).withName("in_addr"),
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle setipv4sourcefilter$MH = RuntimeHelper.downcallHandle(
        "setipv4sourcefilter",
        constants$1378.setipv4sourcefilter$FUNC
    );
}


