// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$566 {

    static final FunctionDescriptor FindWindowExA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindWindowExA$MH = RuntimeHelper.downcallHandle(
        "FindWindowExA",
        constants$566.FindWindowExA$FUNC
    );
    static final FunctionDescriptor FindWindowExW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindWindowExW$MH = RuntimeHelper.downcallHandle(
        "FindWindowExW",
        constants$566.FindWindowExW$FUNC
    );
    static final FunctionDescriptor GetShellWindow$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetShellWindow$MH = RuntimeHelper.downcallHandle(
        "GetShellWindow",
        constants$566.GetShellWindow$FUNC
    );
    static final FunctionDescriptor RegisterShellHookWindow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterShellHookWindow$MH = RuntimeHelper.downcallHandle(
        "RegisterShellHookWindow",
        constants$566.RegisterShellHookWindow$FUNC
    );
    static final FunctionDescriptor DeregisterShellHookWindow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeregisterShellHookWindow$MH = RuntimeHelper.downcallHandle(
        "DeregisterShellHookWindow",
        constants$566.DeregisterShellHookWindow$FUNC
    );
    static final FunctionDescriptor EnumWindows$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumWindows$MH = RuntimeHelper.downcallHandle(
        "EnumWindows",
        constants$566.EnumWindows$FUNC
    );
}


