// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$800 {

    static final FunctionDescriptor BCryptEnumContexts$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptEnumContexts$MH = RuntimeHelper.downcallHandle(
        "BCryptEnumContexts",
        constants$800.BCryptEnumContexts$FUNC
    );
    static final FunctionDescriptor BCryptConfigureContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptConfigureContext$MH = RuntimeHelper.downcallHandle(
        "BCryptConfigureContext",
        constants$800.BCryptConfigureContext$FUNC
    );
    static final FunctionDescriptor BCryptQueryContextConfiguration$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptQueryContextConfiguration$MH = RuntimeHelper.downcallHandle(
        "BCryptQueryContextConfiguration",
        constants$800.BCryptQueryContextConfiguration$FUNC
    );
    static final FunctionDescriptor BCryptAddContextFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle BCryptAddContextFunction$MH = RuntimeHelper.downcallHandle(
        "BCryptAddContextFunction",
        constants$800.BCryptAddContextFunction$FUNC
    );
    static final FunctionDescriptor BCryptRemoveContextFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptRemoveContextFunction$MH = RuntimeHelper.downcallHandle(
        "BCryptRemoveContextFunction",
        constants$800.BCryptRemoveContextFunction$FUNC
    );
    static final FunctionDescriptor BCryptEnumContextFunctions$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptEnumContextFunctions$MH = RuntimeHelper.downcallHandle(
        "BCryptEnumContextFunctions",
        constants$800.BCryptEnumContextFunctions$FUNC
    );
}


