// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$925 {

    static final  GroupLayout GUID_DEVINTERFACE_FLOPPY$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_FLOPPY$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_FLOPPY", constants$925.GUID_DEVINTERFACE_FLOPPY$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_CDCHANGER$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_CDCHANGER$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_CDCHANGER", constants$925.GUID_DEVINTERFACE_CDCHANGER$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_STORAGEPORT$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_STORAGEPORT$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_STORAGEPORT", constants$925.GUID_DEVINTERFACE_STORAGEPORT$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_VMLUN$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_VMLUN$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_VMLUN", constants$925.GUID_DEVINTERFACE_VMLUN$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_SES$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_SES$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_SES", constants$925.GUID_DEVINTERFACE_SES$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_SERVICE_VOLUME$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_SERVICE_VOLUME$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_SERVICE_VOLUME", constants$925.GUID_DEVINTERFACE_SERVICE_VOLUME$LAYOUT);
}


