// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$299 {

    static final FunctionDescriptor CheckTokenMembership$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CheckTokenMembership$MH = RuntimeHelper.downcallHandle(
        "CheckTokenMembership",
        constants$299.CheckTokenMembership$FUNC
    );
    static final FunctionDescriptor CheckTokenCapability$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CheckTokenCapability$MH = RuntimeHelper.downcallHandle(
        "CheckTokenCapability",
        constants$299.CheckTokenCapability$FUNC
    );
    static final FunctionDescriptor GetAppContainerAce$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetAppContainerAce$MH = RuntimeHelper.downcallHandle(
        "GetAppContainerAce",
        constants$299.GetAppContainerAce$FUNC
    );
    static final FunctionDescriptor CheckTokenMembershipEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CheckTokenMembershipEx$MH = RuntimeHelper.downcallHandle(
        "CheckTokenMembershipEx",
        constants$299.CheckTokenMembershipEx$FUNC
    );
    static final FunctionDescriptor ConvertToAutoInheritPrivateObjectSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ConvertToAutoInheritPrivateObjectSecurity$MH = RuntimeHelper.downcallHandle(
        "ConvertToAutoInheritPrivateObjectSecurity",
        constants$299.ConvertToAutoInheritPrivateObjectSecurity$FUNC
    );
    static final FunctionDescriptor CopySid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CopySid$MH = RuntimeHelper.downcallHandle(
        "CopySid",
        constants$299.CopySid$FUNC
    );
}


