// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$790 {

    static final FunctionDescriptor CryptCreateHash$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptCreateHash$MH = RuntimeHelper.downcallHandle(
        "CryptCreateHash",
        constants$790.CryptCreateHash$FUNC
    );
    static final FunctionDescriptor CryptHashData$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptHashData$MH = RuntimeHelper.downcallHandle(
        "CryptHashData",
        constants$790.CryptHashData$FUNC
    );
    static final FunctionDescriptor CryptHashSessionKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CryptHashSessionKey$MH = RuntimeHelper.downcallHandle(
        "CryptHashSessionKey",
        constants$790.CryptHashSessionKey$FUNC
    );
    static final FunctionDescriptor CryptDestroyHash$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle CryptDestroyHash$MH = RuntimeHelper.downcallHandle(
        "CryptDestroyHash",
        constants$790.CryptDestroyHash$FUNC
    );
    static final FunctionDescriptor CryptSignHashA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptSignHashA$MH = RuntimeHelper.downcallHandle(
        "CryptSignHashA",
        constants$790.CryptSignHashA$FUNC
    );
    static final FunctionDescriptor CryptSignHashW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptSignHashW$MH = RuntimeHelper.downcallHandle(
        "CryptSignHashW",
        constants$790.CryptSignHashW$FUNC
    );
}


