// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1395 {

    static final FunctionDescriptor curl_global_cleanup$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle curl_global_cleanup$MH = RuntimeHelper.downcallHandle(
        "curl_global_cleanup",
        constants$1395.curl_global_cleanup$FUNC
    );
    static final FunctionDescriptor curl_global_sslset$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_global_sslset$MH = RuntimeHelper.downcallHandle(
        "curl_global_sslset",
        constants$1395.curl_global_sslset$FUNC
    );
    static final FunctionDescriptor curl_slist_append$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_slist_append$MH = RuntimeHelper.downcallHandle(
        "curl_slist_append",
        constants$1395.curl_slist_append$FUNC
    );
    static final FunctionDescriptor curl_slist_free_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_slist_free_all$MH = RuntimeHelper.downcallHandle(
        "curl_slist_free_all",
        constants$1395.curl_slist_free_all$FUNC
    );
    static final FunctionDescriptor curl_getdate$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_getdate$MH = RuntimeHelper.downcallHandle(
        "curl_getdate",
        constants$1395.curl_getdate$FUNC
    );
    static final FunctionDescriptor curl_lock_function$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


