// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$372 {

    static final FunctionDescriptor OpenEventLogA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenEventLogA$MH = RuntimeHelper.downcallHandle(
        "OpenEventLogA",
        constants$372.OpenEventLogA$FUNC
    );
    static final FunctionDescriptor OpenEventLogW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenEventLogW$MH = RuntimeHelper.downcallHandle(
        "OpenEventLogW",
        constants$372.OpenEventLogW$FUNC
    );
    static final FunctionDescriptor RegisterEventSourceA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterEventSourceA$MH = RuntimeHelper.downcallHandle(
        "RegisterEventSourceA",
        constants$372.RegisterEventSourceA$FUNC
    );
    static final FunctionDescriptor RegisterEventSourceW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterEventSourceW$MH = RuntimeHelper.downcallHandle(
        "RegisterEventSourceW",
        constants$372.RegisterEventSourceW$FUNC
    );
    static final FunctionDescriptor OpenBackupEventLogA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenBackupEventLogA$MH = RuntimeHelper.downcallHandle(
        "OpenBackupEventLogA",
        constants$372.OpenBackupEventLogA$FUNC
    );
    static final FunctionDescriptor OpenBackupEventLogW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenBackupEventLogW$MH = RuntimeHelper.downcallHandle(
        "OpenBackupEventLogW",
        constants$372.OpenBackupEventLogW$FUNC
    );
}


