// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$574 {

    static final FunctionDescriptor GetIconInfoExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetIconInfoExA$MH = RuntimeHelper.downcallHandle(
        "GetIconInfoExA",
        constants$574.GetIconInfoExA$FUNC
    );
    static final FunctionDescriptor GetIconInfoExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetIconInfoExW$MH = RuntimeHelper.downcallHandle(
        "GetIconInfoExW",
        constants$574.GetIconInfoExW$FUNC
    );
    static final FunctionDescriptor IsDialogMessageA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IsDialogMessageA$MH = RuntimeHelper.downcallHandle(
        "IsDialogMessageA",
        constants$574.IsDialogMessageA$FUNC
    );
    static final FunctionDescriptor IsDialogMessageW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IsDialogMessageW$MH = RuntimeHelper.downcallHandle(
        "IsDialogMessageW",
        constants$574.IsDialogMessageW$FUNC
    );
    static final FunctionDescriptor MapDialogRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MapDialogRect$MH = RuntimeHelper.downcallHandle(
        "MapDialogRect",
        constants$574.MapDialogRect$FUNC
    );
    static final FunctionDescriptor DlgDirListA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DlgDirListA$MH = RuntimeHelper.downcallHandle(
        "DlgDirListA",
        constants$574.DlgDirListA$FUNC
    );
}


