// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$289 {

    static final FunctionDescriptor FreeLibrary$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FreeLibrary$MH = RuntimeHelper.downcallHandle(
        "FreeLibrary",
        constants$289.FreeLibrary$FUNC
    );
    static final FunctionDescriptor FreeLibraryAndExitThread$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle FreeLibraryAndExitThread$MH = RuntimeHelper.downcallHandle(
        "FreeLibraryAndExitThread",
        constants$289.FreeLibraryAndExitThread$FUNC
    );
    static final FunctionDescriptor FreeResource$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FreeResource$MH = RuntimeHelper.downcallHandle(
        "FreeResource",
        constants$289.FreeResource$FUNC
    );
    static final FunctionDescriptor GetModuleFileNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetModuleFileNameA$MH = RuntimeHelper.downcallHandle(
        "GetModuleFileNameA",
        constants$289.GetModuleFileNameA$FUNC
    );
    static final FunctionDescriptor GetModuleFileNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetModuleFileNameW$MH = RuntimeHelper.downcallHandle(
        "GetModuleFileNameW",
        constants$289.GetModuleFileNameW$FUNC
    );
    static final FunctionDescriptor GetModuleHandleA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetModuleHandleA$MH = RuntimeHelper.downcallHandle(
        "GetModuleHandleA",
        constants$289.GetModuleHandleA$FUNC
    );
}


