// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$636 {

    static final FunctionDescriptor SetConsoleTitleA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleTitleA$MH = RuntimeHelper.downcallHandle(
        "SetConsoleTitleA",
        constants$636.SetConsoleTitleA$FUNC
    );
    static final FunctionDescriptor SetConsoleTitleW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleTitleW$MH = RuntimeHelper.downcallHandle(
        "SetConsoleTitleW",
        constants$636.SetConsoleTitleW$FUNC
    );
    static final FunctionDescriptor GetNumberOfConsoleMouseButtons$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetNumberOfConsoleMouseButtons$MH = RuntimeHelper.downcallHandle(
        "GetNumberOfConsoleMouseButtons",
        constants$636.GetNumberOfConsoleMouseButtons$FUNC
    );
    static final FunctionDescriptor GetConsoleFontSize$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("X"),
        Constants$root.C_SHORT$LAYOUT.withName("Y")
    ).withName("_COORD"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetConsoleFontSize$MH = RuntimeHelper.downcallHandle(
        "GetConsoleFontSize",
        constants$636.GetConsoleFontSize$FUNC
    );
    static final FunctionDescriptor GetCurrentConsoleFont$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCurrentConsoleFont$MH = RuntimeHelper.downcallHandle(
        "GetCurrentConsoleFont",
        constants$636.GetCurrentConsoleFont$FUNC
    );
    static final FunctionDescriptor GetCurrentConsoleFontEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCurrentConsoleFontEx$MH = RuntimeHelper.downcallHandle(
        "GetCurrentConsoleFontEx",
        constants$636.GetCurrentConsoleFontEx$FUNC
    );
}


