// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$218 {

    static final FunctionDescriptor PTOP_LEVEL_EXCEPTION_FILTER$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PTOP_LEVEL_EXCEPTION_FILTER$MH = RuntimeHelper.downcallHandle(
        constants$218.PTOP_LEVEL_EXCEPTION_FILTER$FUNC
    );
    static final FunctionDescriptor LPTOP_LEVEL_EXCEPTION_FILTER$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LPTOP_LEVEL_EXCEPTION_FILTER$MH = RuntimeHelper.downcallHandle(
        constants$218.LPTOP_LEVEL_EXCEPTION_FILTER$FUNC
    );
    static final FunctionDescriptor RaiseException$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RaiseException$MH = RuntimeHelper.downcallHandle(
        "RaiseException",
        constants$218.RaiseException$FUNC
    );
    static final FunctionDescriptor UnhandledExceptionFilter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnhandledExceptionFilter$MH = RuntimeHelper.downcallHandle(
        "UnhandledExceptionFilter",
        constants$218.UnhandledExceptionFilter$FUNC
    );
    static final FunctionDescriptor SetUnhandledExceptionFilter$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetUnhandledExceptionFilter$MH = RuntimeHelper.downcallHandle(
        "SetUnhandledExceptionFilter",
        constants$218.SetUnhandledExceptionFilter$FUNC
    );
}


