// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$615 {

    static final FunctionDescriptor GetSystemDefaultUILanguage$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT);
    static final MethodHandle GetSystemDefaultUILanguage$MH = RuntimeHelper.downcallHandle(
        "GetSystemDefaultUILanguage",
        constants$615.GetSystemDefaultUILanguage$FUNC
    );
    static final FunctionDescriptor GetThreadLocale$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle GetThreadLocale$MH = RuntimeHelper.downcallHandle(
        "GetThreadLocale",
        constants$615.GetThreadLocale$FUNC
    );
    static final FunctionDescriptor SetThreadLocale$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetThreadLocale$MH = RuntimeHelper.downcallHandle(
        "SetThreadLocale",
        constants$615.SetThreadLocale$FUNC
    );
    static final FunctionDescriptor GetUserDefaultUILanguage$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT);
    static final MethodHandle GetUserDefaultUILanguage$MH = RuntimeHelper.downcallHandle(
        "GetUserDefaultUILanguage",
        constants$615.GetUserDefaultUILanguage$FUNC
    );
    static final FunctionDescriptor GetUserDefaultLangID$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT);
    static final MethodHandle GetUserDefaultLangID$MH = RuntimeHelper.downcallHandle(
        "GetUserDefaultLangID",
        constants$615.GetUserDefaultLangID$FUNC
    );
    static final FunctionDescriptor GetSystemDefaultLangID$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT);
    static final MethodHandle GetSystemDefaultLangID$MH = RuntimeHelper.downcallHandle(
        "GetSystemDefaultLangID",
        constants$615.GetSystemDefaultLangID$FUNC
    );
}


