// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$490 {

    static final FunctionDescriptor SendMessageCallbackW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SendMessageCallbackW$MH = RuntimeHelper.downcallHandle(
        "SendMessageCallbackW",
        constants$490.SendMessageCallbackW$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageExA$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageExA",
        constants$490.BroadcastSystemMessageExA$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageExW$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageExW",
        constants$490.BroadcastSystemMessageExW$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageA$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageA",
        constants$490.BroadcastSystemMessageA$FUNC
    );
    static final FunctionDescriptor BroadcastSystemMessageW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle BroadcastSystemMessageW$MH = RuntimeHelper.downcallHandle(
        "BroadcastSystemMessageW",
        constants$490.BroadcastSystemMessageW$FUNC
    );
    static final FunctionDescriptor RegisterDeviceNotificationA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegisterDeviceNotificationA$MH = RuntimeHelper.downcallHandle(
        "RegisterDeviceNotificationA",
        constants$490.RegisterDeviceNotificationA$FUNC
    );
}


