// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$74 {

    static final FunctionDescriptor _isdigit_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _isdigit_l$MH = RuntimeHelper.downcallHandle(
        "_isdigit_l",
        constants$74._isdigit_l$FUNC
    );
    static final FunctionDescriptor isxdigit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle isxdigit$MH = RuntimeHelper.downcallHandle(
        "isxdigit",
        constants$74.isxdigit$FUNC
    );
    static final FunctionDescriptor _isxdigit_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _isxdigit_l$MH = RuntimeHelper.downcallHandle(
        "_isxdigit_l",
        constants$74._isxdigit_l$FUNC
    );
    static final FunctionDescriptor isspace$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle isspace$MH = RuntimeHelper.downcallHandle(
        "isspace",
        constants$74.isspace$FUNC
    );
    static final FunctionDescriptor _isspace_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _isspace_l$MH = RuntimeHelper.downcallHandle(
        "_isspace_l",
        constants$74._isspace_l$FUNC
    );
    static final FunctionDescriptor ispunct$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ispunct$MH = RuntimeHelper.downcallHandle(
        "ispunct",
        constants$74.ispunct$FUNC
    );
}


