// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$725 {

    static final FunctionDescriptor RpcNsBindingInqEntryNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingInqEntryNameA$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingInqEntryNameA",
        constants$725.RpcNsBindingInqEntryNameA$FUNC
    );
    static final FunctionDescriptor RpcNsBindingInqEntryNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcNsBindingInqEntryNameW$MH = RuntimeHelper.downcallHandle(
        "RpcNsBindingInqEntryNameW",
        constants$725.RpcNsBindingInqEntryNameW$FUNC
    );
    static final FunctionDescriptor RpcBindingCreateA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingCreateA$MH = RuntimeHelper.downcallHandle(
        "RpcBindingCreateA",
        constants$725.RpcBindingCreateA$FUNC
    );
    static final FunctionDescriptor RpcBindingCreateW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingCreateW$MH = RuntimeHelper.downcallHandle(
        "RpcBindingCreateW",
        constants$725.RpcBindingCreateW$FUNC
    );
    static final FunctionDescriptor RpcBindingGetTrainingContextHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingGetTrainingContextHandle$MH = RuntimeHelper.downcallHandle(
        "RpcBindingGetTrainingContextHandle",
        constants$725.RpcBindingGetTrainingContextHandle$FUNC
    );
    static final FunctionDescriptor RpcServerInqBindingHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerInqBindingHandle$MH = RuntimeHelper.downcallHandle(
        "RpcServerInqBindingHandle",
        constants$725.RpcServerInqBindingHandle$FUNC
    );
}


