// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$246 {

    static final FunctionDescriptor CreateProcessAsUserW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateProcessAsUserW$MH = RuntimeHelper.downcallHandle(
        "CreateProcessAsUserW",
        constants$246.CreateProcessAsUserW$FUNC
    );
    static final FunctionDescriptor GetCurrentProcessToken$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetCurrentProcessToken$MH = RuntimeHelper.downcallHandle(
        "GetCurrentProcessToken",
        constants$246.GetCurrentProcessToken$FUNC
    );
    static final FunctionDescriptor GetCurrentThreadToken$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetCurrentThreadToken$MH = RuntimeHelper.downcallHandle(
        "GetCurrentThreadToken",
        constants$246.GetCurrentThreadToken$FUNC
    );
    static final FunctionDescriptor GetCurrentThreadEffectiveToken$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetCurrentThreadEffectiveToken$MH = RuntimeHelper.downcallHandle(
        "GetCurrentThreadEffectiveToken",
        constants$246.GetCurrentThreadEffectiveToken$FUNC
    );
    static final FunctionDescriptor SetThreadToken$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetThreadToken$MH = RuntimeHelper.downcallHandle(
        "SetThreadToken",
        constants$246.SetThreadToken$FUNC
    );
    static final FunctionDescriptor OpenProcessToken$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenProcessToken$MH = RuntimeHelper.downcallHandle(
        "OpenProcessToken",
        constants$246.OpenProcessToken$FUNC
    );
}


