// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1053 {

    static final FunctionDescriptor CoRevokeClassObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CoRevokeClassObject$MH = RuntimeHelper.downcallHandle(
        "CoRevokeClassObject",
        constants$1053.CoRevokeClassObject$FUNC
    );
    static final FunctionDescriptor CoResumeClassObjects$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoResumeClassObjects$MH = RuntimeHelper.downcallHandle(
        "CoResumeClassObjects",
        constants$1053.CoResumeClassObjects$FUNC
    );
    static final FunctionDescriptor CoSuspendClassObjects$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoSuspendClassObjects$MH = RuntimeHelper.downcallHandle(
        "CoSuspendClassObjects",
        constants$1053.CoSuspendClassObjects$FUNC
    );
    static final FunctionDescriptor CoAddRefServerProcess$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoAddRefServerProcess$MH = RuntimeHelper.downcallHandle(
        "CoAddRefServerProcess",
        constants$1053.CoAddRefServerProcess$FUNC
    );
    static final FunctionDescriptor CoReleaseServerProcess$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoReleaseServerProcess$MH = RuntimeHelper.downcallHandle(
        "CoReleaseServerProcess",
        constants$1053.CoReleaseServerProcess$FUNC
    );
    static final FunctionDescriptor CoGetPSClsid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetPSClsid$MH = RuntimeHelper.downcallHandle(
        "CoGetPSClsid",
        constants$1053.CoGetPSClsid$FUNC
    );
}


