// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$439 {

    static final FunctionDescriptor SetMapperFlags$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetMapperFlags$MH = RuntimeHelper.downcallHandle(
        "SetMapperFlags",
        constants$439.SetMapperFlags$FUNC
    );
    static final FunctionDescriptor SetGraphicsMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetGraphicsMode$MH = RuntimeHelper.downcallHandle(
        "SetGraphicsMode",
        constants$439.SetGraphicsMode$FUNC
    );
    static final FunctionDescriptor SetMapMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetMapMode$MH = RuntimeHelper.downcallHandle(
        "SetMapMode",
        constants$439.SetMapMode$FUNC
    );
    static final FunctionDescriptor SetLayout$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetLayout$MH = RuntimeHelper.downcallHandle(
        "SetLayout",
        constants$439.SetLayout$FUNC
    );
    static final FunctionDescriptor GetLayout$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetLayout$MH = RuntimeHelper.downcallHandle(
        "GetLayout",
        constants$439.GetLayout$FUNC
    );
    static final FunctionDescriptor SetMetaFileBitsEx$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetMetaFileBitsEx$MH = RuntimeHelper.downcallHandle(
        "SetMetaFileBitsEx",
        constants$439.SetMetaFileBitsEx$FUNC
    );
}


