// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$460 {

    static final FunctionDescriptor GetKerningPairsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetKerningPairsA$MH = RuntimeHelper.downcallHandle(
        "GetKerningPairsA",
        constants$460.GetKerningPairsA$FUNC
    );
    static final FunctionDescriptor GetKerningPairsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetKerningPairsW$MH = RuntimeHelper.downcallHandle(
        "GetKerningPairsW",
        constants$460.GetKerningPairsW$FUNC
    );
    static final FunctionDescriptor GetDCOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDCOrgEx$MH = RuntimeHelper.downcallHandle(
        "GetDCOrgEx",
        constants$460.GetDCOrgEx$FUNC
    );
    static final FunctionDescriptor FixBrushOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FixBrushOrgEx$MH = RuntimeHelper.downcallHandle(
        "FixBrushOrgEx",
        constants$460.FixBrushOrgEx$FUNC
    );
    static final FunctionDescriptor UnrealizeObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnrealizeObject$MH = RuntimeHelper.downcallHandle(
        "UnrealizeObject",
        constants$460.UnrealizeObject$FUNC
    );
    static final FunctionDescriptor GdiFlush$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle GdiFlush$MH = RuntimeHelper.downcallHandle(
        "GdiFlush",
        constants$460.GdiFlush$FUNC
    );
}


