// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1314 {

    static final FunctionDescriptor FindTextA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindTextA$MH = RuntimeHelper.downcallHandle(
        "FindTextA",
        constants$1314.FindTextA$FUNC
    );
    static final FunctionDescriptor FindTextW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FindTextW$MH = RuntimeHelper.downcallHandle(
        "FindTextW",
        constants$1314.FindTextW$FUNC
    );
    static final FunctionDescriptor ReplaceTextA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReplaceTextA$MH = RuntimeHelper.downcallHandle(
        "ReplaceTextA",
        constants$1314.ReplaceTextA$FUNC
    );
    static final FunctionDescriptor ReplaceTextW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReplaceTextW$MH = RuntimeHelper.downcallHandle(
        "ReplaceTextW",
        constants$1314.ReplaceTextW$FUNC
    );
    static final FunctionDescriptor LPCFHOOKPROC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LPCFHOOKPROC$MH = RuntimeHelper.downcallHandle(
        constants$1314.LPCFHOOKPROC$FUNC
    );
}


