// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$438 {

    static final FunctionDescriptor SetDCPenColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetDCPenColor$MH = RuntimeHelper.downcallHandle(
        "SetDCPenColor",
        constants$438.SetDCPenColor$FUNC
    );
    static final FunctionDescriptor SetBkMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetBkMode$MH = RuntimeHelper.downcallHandle(
        "SetBkMode",
        constants$438.SetBkMode$FUNC
    );
    static final FunctionDescriptor SetBitmapBits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetBitmapBits$MH = RuntimeHelper.downcallHandle(
        "SetBitmapBits",
        constants$438.SetBitmapBits$FUNC
    );
    static final FunctionDescriptor SetBoundsRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetBoundsRect$MH = RuntimeHelper.downcallHandle(
        "SetBoundsRect",
        constants$438.SetBoundsRect$FUNC
    );
    static final FunctionDescriptor SetDIBits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetDIBits$MH = RuntimeHelper.downcallHandle(
        "SetDIBits",
        constants$438.SetDIBits$FUNC
    );
    static final FunctionDescriptor SetDIBitsToDevice$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetDIBitsToDevice$MH = RuntimeHelper.downcallHandle(
        "SetDIBitsToDevice",
        constants$438.SetDIBitsToDevice$FUNC
    );
}


