// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$347 {

    static final FunctionDescriptor QueryFullProcessImageNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryFullProcessImageNameA$MH = RuntimeHelper.downcallHandle(
        "QueryFullProcessImageNameA",
        constants$347.QueryFullProcessImageNameA$FUNC
    );
    static final FunctionDescriptor QueryFullProcessImageNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryFullProcessImageNameW$MH = RuntimeHelper.downcallHandle(
        "QueryFullProcessImageNameW",
        constants$347.QueryFullProcessImageNameW$FUNC
    );
    static final FunctionDescriptor GetStartupInfoA$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetStartupInfoA$MH = RuntimeHelper.downcallHandle(
        "GetStartupInfoA",
        constants$347.GetStartupInfoA$FUNC
    );
    static final FunctionDescriptor GetFirmwareEnvironmentVariableA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetFirmwareEnvironmentVariableA$MH = RuntimeHelper.downcallHandle(
        "GetFirmwareEnvironmentVariableA",
        constants$347.GetFirmwareEnvironmentVariableA$FUNC
    );
    static final FunctionDescriptor GetFirmwareEnvironmentVariableW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetFirmwareEnvironmentVariableW$MH = RuntimeHelper.downcallHandle(
        "GetFirmwareEnvironmentVariableW",
        constants$347.GetFirmwareEnvironmentVariableW$FUNC
    );
    static final FunctionDescriptor GetFirmwareEnvironmentVariableExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFirmwareEnvironmentVariableExA$MH = RuntimeHelper.downcallHandle(
        "GetFirmwareEnvironmentVariableExA",
        constants$347.GetFirmwareEnvironmentVariableExA$FUNC
    );
}


