// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$231 {

    static final FunctionDescriptor SetCriticalSectionSpinCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetCriticalSectionSpinCount$MH = RuntimeHelper.downcallHandle(
        "SetCriticalSectionSpinCount",
        constants$231.SetCriticalSectionSpinCount$FUNC
    );
    static final FunctionDescriptor TryEnterCriticalSection$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle TryEnterCriticalSection$MH = RuntimeHelper.downcallHandle(
        "TryEnterCriticalSection",
        constants$231.TryEnterCriticalSection$FUNC
    );
    static final FunctionDescriptor DeleteCriticalSection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeleteCriticalSection$MH = RuntimeHelper.downcallHandle(
        "DeleteCriticalSection",
        constants$231.DeleteCriticalSection$FUNC
    );
    static final FunctionDescriptor PINIT_ONCE_FN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PINIT_ONCE_FN$MH = RuntimeHelper.downcallHandle(
        constants$231.PINIT_ONCE_FN$FUNC
    );
    static final FunctionDescriptor InitOnceInitialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle InitOnceInitialize$MH = RuntimeHelper.downcallHandle(
        "InitOnceInitialize",
        constants$231.InitOnceInitialize$FUNC
    );
}


