// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$70 {

    static final FunctionDescriptor _iswpunct_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswpunct_l$MH = RuntimeHelper.downcallHandle(
        "_iswpunct_l",
        constants$70._iswpunct_l$FUNC
    );
    static final FunctionDescriptor _iswspace_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswspace_l$MH = RuntimeHelper.downcallHandle(
        "_iswspace_l",
        constants$70._iswspace_l$FUNC
    );
    static final FunctionDescriptor _iswupper_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswupper_l$MH = RuntimeHelper.downcallHandle(
        "_iswupper_l",
        constants$70._iswupper_l$FUNC
    );
    static final FunctionDescriptor _iswxdigit_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswxdigit_l$MH = RuntimeHelper.downcallHandle(
        "_iswxdigit_l",
        constants$70._iswxdigit_l$FUNC
    );
    static final FunctionDescriptor _iswcsymf_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswcsymf_l$MH = RuntimeHelper.downcallHandle(
        "_iswcsymf_l",
        constants$70._iswcsymf_l$FUNC
    );
    static final FunctionDescriptor _iswcsym_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswcsym_l$MH = RuntimeHelper.downcallHandle(
        "_iswcsym_l",
        constants$70._iswcsym_l$FUNC
    );
}


