// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1289 {

    static final FunctionDescriptor VarCmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle VarCmp$MH = RuntimeHelper.downcallHandle(
        "VarCmp",
        constants$1289.VarCmp$FUNC
    );
    static final FunctionDescriptor VarDecAdd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarDecAdd$MH = RuntimeHelper.downcallHandle(
        "VarDecAdd",
        constants$1289.VarDecAdd$FUNC
    );
    static final FunctionDescriptor VarDecDiv$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarDecDiv$MH = RuntimeHelper.downcallHandle(
        "VarDecDiv",
        constants$1289.VarDecDiv$FUNC
    );
    static final FunctionDescriptor VarDecMul$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarDecMul$MH = RuntimeHelper.downcallHandle(
        "VarDecMul",
        constants$1289.VarDecMul$FUNC
    );
    static final FunctionDescriptor VarDecSub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarDecSub$MH = RuntimeHelper.downcallHandle(
        "VarDecSub",
        constants$1289.VarDecSub$FUNC
    );
    static final FunctionDescriptor VarDecAbs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarDecAbs$MH = RuntimeHelper.downcallHandle(
        "VarDecAbs",
        constants$1289.VarDecAbs$FUNC
    );
}


