// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$637 {

    static final FunctionDescriptor SetCurrentConsoleFontEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetCurrentConsoleFontEx$MH = RuntimeHelper.downcallHandle(
        "SetCurrentConsoleFontEx",
        constants$637.SetCurrentConsoleFontEx$FUNC
    );
    static final FunctionDescriptor GetConsoleSelectionInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetConsoleSelectionInfo$MH = RuntimeHelper.downcallHandle(
        "GetConsoleSelectionInfo",
        constants$637.GetConsoleSelectionInfo$FUNC
    );
    static final FunctionDescriptor GetConsoleHistoryInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetConsoleHistoryInfo$MH = RuntimeHelper.downcallHandle(
        "GetConsoleHistoryInfo",
        constants$637.GetConsoleHistoryInfo$FUNC
    );
    static final FunctionDescriptor SetConsoleHistoryInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleHistoryInfo$MH = RuntimeHelper.downcallHandle(
        "SetConsoleHistoryInfo",
        constants$637.SetConsoleHistoryInfo$FUNC
    );
    static final FunctionDescriptor GetConsoleDisplayMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetConsoleDisplayMode$MH = RuntimeHelper.downcallHandle(
        "GetConsoleDisplayMode",
        constants$637.GetConsoleDisplayMode$FUNC
    );
    static final FunctionDescriptor SetConsoleDisplayMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleDisplayMode$MH = RuntimeHelper.downcallHandle(
        "SetConsoleDisplayMode",
        constants$637.SetConsoleDisplayMode$FUNC
    );
}


