// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$744 {

    static final FunctionDescriptor I_RpcNsInterfaceUnexported$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcNsInterfaceUnexported$MH = RuntimeHelper.downcallHandle(
        "I_RpcNsInterfaceUnexported",
        constants$744.I_RpcNsInterfaceUnexported$FUNC
    );
    static final FunctionDescriptor I_RpcBindingToStaticStringBindingW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingToStaticStringBindingW$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingToStaticStringBindingW",
        constants$744.I_RpcBindingToStaticStringBindingW$FUNC
    );
    static final FunctionDescriptor I_RpcBindingInqSecurityContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingInqSecurityContext$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingInqSecurityContext",
        constants$744.I_RpcBindingInqSecurityContext$FUNC
    );
    static final FunctionDescriptor I_RpcBindingInqSecurityContextKeyInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingInqSecurityContextKeyInfo$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingInqSecurityContextKeyInfo",
        constants$744.I_RpcBindingInqSecurityContextKeyInfo$FUNC
    );
    static final FunctionDescriptor I_RpcBindingInqWireIdForSnego$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingInqWireIdForSnego$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingInqWireIdForSnego",
        constants$744.I_RpcBindingInqWireIdForSnego$FUNC
    );
    static final FunctionDescriptor I_RpcBindingInqMarshalledTargetInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingInqMarshalledTargetInfo$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingInqMarshalledTargetInfo",
        constants$744.I_RpcBindingInqMarshalledTargetInfo$FUNC
    );
}


