// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$901 {

    static final FunctionDescriptor NdrPointerFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrPointerFree$MH = RuntimeHelper.downcallHandle(
        "NdrPointerFree",
        constants$901.NdrPointerFree$FUNC
    );
    static final FunctionDescriptor NdrCsArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrCsArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrCsArrayFree",
        constants$901.NdrCsArrayFree$FUNC
    );
    static final FunctionDescriptor NdrSimpleStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrSimpleStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrSimpleStructFree",
        constants$901.NdrSimpleStructFree$FUNC
    );
    static final FunctionDescriptor NdrConformantStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConformantStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrConformantStructFree",
        constants$901.NdrConformantStructFree$FUNC
    );
    static final FunctionDescriptor NdrConformantVaryingStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConformantVaryingStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrConformantVaryingStructFree",
        constants$901.NdrConformantVaryingStructFree$FUNC
    );
    static final FunctionDescriptor NdrComplexStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrComplexStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrComplexStructFree",
        constants$901.NdrComplexStructFree$FUNC
    );
}


