// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$667 {

    static final FunctionDescriptor WNetGetNetworkInformationW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetNetworkInformationW$MH = RuntimeHelper.downcallHandle(
        "WNetGetNetworkInformationW",
        constants$667.WNetGetNetworkInformationW$FUNC
    );
    static final FunctionDescriptor WNetGetLastErrorA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetGetLastErrorA$MH = RuntimeHelper.downcallHandle(
        "WNetGetLastErrorA",
        constants$667.WNetGetLastErrorA$FUNC
    );
    static final FunctionDescriptor WNetGetLastErrorW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetGetLastErrorW$MH = RuntimeHelper.downcallHandle(
        "WNetGetLastErrorW",
        constants$667.WNetGetLastErrorW$FUNC
    );
    static final FunctionDescriptor MultinetGetConnectionPerformanceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MultinetGetConnectionPerformanceA$MH = RuntimeHelper.downcallHandle(
        "MultinetGetConnectionPerformanceA",
        constants$667.MultinetGetConnectionPerformanceA$FUNC
    );
    static final FunctionDescriptor MultinetGetConnectionPerformanceW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MultinetGetConnectionPerformanceW$MH = RuntimeHelper.downcallHandle(
        "MultinetGetConnectionPerformanceW",
        constants$667.MultinetGetConnectionPerformanceW$FUNC
    );
    static final FunctionDescriptor DdeSetQualityOfService$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdeSetQualityOfService$MH = RuntimeHelper.downcallHandle(
        "DdeSetQualityOfService",
        constants$667.DdeSetQualityOfService$FUNC
    );
}


