// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$839 {

    static final FunctionDescriptor PFN_CERT_CREATE_CONTEXT_SORT_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CERT_CREATE_CONTEXT_SORT_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$839.PFN_CERT_CREATE_CONTEXT_SORT_FUNC$FUNC
    );
    static final FunctionDescriptor CertCreateContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertCreateContext$MH = RuntimeHelper.downcallHandle(
        "CertCreateContext",
        constants$839.CertCreateContext$FUNC
    );
    static final FunctionDescriptor CertRegisterSystemStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertRegisterSystemStore$MH = RuntimeHelper.downcallHandle(
        "CertRegisterSystemStore",
        constants$839.CertRegisterSystemStore$FUNC
    );
    static final FunctionDescriptor CertRegisterPhysicalStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertRegisterPhysicalStore$MH = RuntimeHelper.downcallHandle(
        "CertRegisterPhysicalStore",
        constants$839.CertRegisterPhysicalStore$FUNC
    );
    static final FunctionDescriptor CertUnregisterSystemStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CertUnregisterSystemStore$MH = RuntimeHelper.downcallHandle(
        "CertUnregisterSystemStore",
        constants$839.CertUnregisterSystemStore$FUNC
    );
}


