// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1688 {

    static final MemorySegment SC_AGGREGATE_STORAGE_KEY$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("S");
    static final MemoryAddress WSA_INVALID_EVENT$ADDR = MemoryAddress.ofLong(0L);
    static final MemorySegment SERVICE_TYPE_VALUE_IPXPORTA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("IpxSocket");
    static final MemorySegment SERVICE_TYPE_VALUE_IPXPORTW$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("I");
    static final MemorySegment SERVICE_TYPE_VALUE_SAPIDA$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SapId");
    static final MemorySegment SERVICE_TYPE_VALUE_SAPIDW$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("S");
}


