// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1044 {

    static final  GroupLayout CLSID_CCDPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDPropertyPage", constants$1044.CLSID_CCDPropertyPage$LAYOUT);
    static final  GroupLayout CLSID_CCDFormDialog$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDFormDialog$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDFormDialog", constants$1044.CLSID_CCDFormDialog$LAYOUT);
    static final  GroupLayout CLSID_CCDCommandButton$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDCommandButton$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDCommandButton", constants$1044.CLSID_CCDCommandButton$LAYOUT);
    static final  GroupLayout CLSID_CCDComboBox$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDComboBox$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDComboBox", constants$1044.CLSID_CCDComboBox$LAYOUT);
    static final  GroupLayout CLSID_CCDTextBox$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDTextBox$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDTextBox", constants$1044.CLSID_CCDTextBox$LAYOUT);
    static final  GroupLayout CLSID_CCDCheckBox$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDCheckBox$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDCheckBox", constants$1044.CLSID_CCDCheckBox$LAYOUT);
}


