// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$418 {

    static final FunctionDescriptor GetROP2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetROP2$MH = RuntimeHelper.downcallHandle(
        "GetROP2",
        constants$418.GetROP2$FUNC
    );
    static final FunctionDescriptor GetAspectRatioFilterEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetAspectRatioFilterEx$MH = RuntimeHelper.downcallHandle(
        "GetAspectRatioFilterEx",
        constants$418.GetAspectRatioFilterEx$FUNC
    );
    static final FunctionDescriptor GetBkColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBkColor$MH = RuntimeHelper.downcallHandle(
        "GetBkColor",
        constants$418.GetBkColor$FUNC
    );
    static final FunctionDescriptor GetDCBrushColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDCBrushColor$MH = RuntimeHelper.downcallHandle(
        "GetDCBrushColor",
        constants$418.GetDCBrushColor$FUNC
    );
    static final FunctionDescriptor GetDCPenColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDCPenColor$MH = RuntimeHelper.downcallHandle(
        "GetDCPenColor",
        constants$418.GetDCPenColor$FUNC
    );
    static final FunctionDescriptor GetBkMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBkMode$MH = RuntimeHelper.downcallHandle(
        "GetBkMode",
        constants$418.GetBkMode$FUNC
    );
}


