// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$671 {

    static final FunctionDescriptor DdeQueryConvInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdeQueryConvInfo$MH = RuntimeHelper.downcallHandle(
        "DdeQueryConvInfo",
        constants$671.DdeQueryConvInfo$FUNC
    );
    static final FunctionDescriptor DdeSetUserHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DdeSetUserHandle$MH = RuntimeHelper.downcallHandle(
        "DdeSetUserHandle",
        constants$671.DdeSetUserHandle$FUNC
    );
    static final FunctionDescriptor DdeAbandonTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeAbandonTransaction$MH = RuntimeHelper.downcallHandle(
        "DdeAbandonTransaction",
        constants$671.DdeAbandonTransaction$FUNC
    );
    static final FunctionDescriptor DdePostAdvise$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdePostAdvise$MH = RuntimeHelper.downcallHandle(
        "DdePostAdvise",
        constants$671.DdePostAdvise$FUNC
    );
    static final FunctionDescriptor DdeEnableCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeEnableCallback$MH = RuntimeHelper.downcallHandle(
        "DdeEnableCallback",
        constants$671.DdeEnableCallback$FUNC
    );
    static final FunctionDescriptor DdeImpersonateClient$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdeImpersonateClient$MH = RuntimeHelper.downcallHandle(
        "DdeImpersonateClient",
        constants$671.DdeImpersonateClient$FUNC
    );
}


