// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1331 {

    static final FunctionDescriptor QueryServiceObjectSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceObjectSecurity$MH = RuntimeHelper.downcallHandle(
        "QueryServiceObjectSecurity",
        constants$1331.QueryServiceObjectSecurity$FUNC
    );
    static final FunctionDescriptor QueryServiceStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceStatus$MH = RuntimeHelper.downcallHandle(
        "QueryServiceStatus",
        constants$1331.QueryServiceStatus$FUNC
    );
    static final FunctionDescriptor QueryServiceStatusEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryServiceStatusEx$MH = RuntimeHelper.downcallHandle(
        "QueryServiceStatusEx",
        constants$1331.QueryServiceStatusEx$FUNC
    );
    static final FunctionDescriptor RegisterServiceCtrlHandlerA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterServiceCtrlHandlerA$MH = RuntimeHelper.downcallHandle(
        "RegisterServiceCtrlHandlerA",
        constants$1331.RegisterServiceCtrlHandlerA$FUNC
    );
    static final FunctionDescriptor RegisterServiceCtrlHandlerW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterServiceCtrlHandlerW$MH = RuntimeHelper.downcallHandle(
        "RegisterServiceCtrlHandlerW",
        constants$1331.RegisterServiceCtrlHandlerW$FUNC
    );
    static final FunctionDescriptor RegisterServiceCtrlHandlerExA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegisterServiceCtrlHandlerExA$MH = RuntimeHelper.downcallHandle(
        "RegisterServiceCtrlHandlerExA",
        constants$1331.RegisterServiceCtrlHandlerExA$FUNC
    );
}


