// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$424 {

    static final FunctionDescriptor GetNearestPaletteIndex$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetNearestPaletteIndex$MH = RuntimeHelper.downcallHandle(
        "GetNearestPaletteIndex",
        constants$424.GetNearestPaletteIndex$FUNC
    );
    static final FunctionDescriptor GetObjectType$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetObjectType$MH = RuntimeHelper.downcallHandle(
        "GetObjectType",
        constants$424.GetObjectType$FUNC
    );
    static final FunctionDescriptor GetOutlineTextMetricsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetOutlineTextMetricsA$MH = RuntimeHelper.downcallHandle(
        "GetOutlineTextMetricsA",
        constants$424.GetOutlineTextMetricsA$FUNC
    );
    static final FunctionDescriptor GetOutlineTextMetricsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetOutlineTextMetricsW$MH = RuntimeHelper.downcallHandle(
        "GetOutlineTextMetricsW",
        constants$424.GetOutlineTextMetricsW$FUNC
    );
    static final FunctionDescriptor GetPaletteEntries$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPaletteEntries$MH = RuntimeHelper.downcallHandle(
        "GetPaletteEntries",
        constants$424.GetPaletteEntries$FUNC
    );
    static final FunctionDescriptor GetPixel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetPixel$MH = RuntimeHelper.downcallHandle(
        "GetPixel",
        constants$424.GetPixel$FUNC
    );
}


