// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$378 {

    static final FunctionDescriptor LookupAccountSidW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountSidW$MH = RuntimeHelper.downcallHandle(
        "LookupAccountSidW",
        constants$378.LookupAccountSidW$FUNC
    );
    static final FunctionDescriptor LookupAccountNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountNameA$MH = RuntimeHelper.downcallHandle(
        "LookupAccountNameA",
        constants$378.LookupAccountNameA$FUNC
    );
    static final FunctionDescriptor LookupAccountNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountNameW$MH = RuntimeHelper.downcallHandle(
        "LookupAccountNameW",
        constants$378.LookupAccountNameW$FUNC
    );
    static final FunctionDescriptor LookupAccountNameLocalA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountNameLocalA$MH = RuntimeHelper.downcallHandle(
        "LookupAccountNameLocalA",
        constants$378.LookupAccountNameLocalA$FUNC
    );
    static final FunctionDescriptor LookupAccountNameLocalW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountNameLocalW$MH = RuntimeHelper.downcallHandle(
        "LookupAccountNameLocalW",
        constants$378.LookupAccountNameLocalW$FUNC
    );
    static final FunctionDescriptor LookupAccountSidLocalA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle LookupAccountSidLocalA$MH = RuntimeHelper.downcallHandle(
        "LookupAccountSidLocalA",
        constants$378.LookupAccountSidLocalA$FUNC
    );
}


