// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$731 {

    static final FunctionDescriptor RpcServerTestCancel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerTestCancel$MH = RuntimeHelper.downcallHandle(
        "RpcServerTestCancel",
        constants$731.RpcServerTestCancel$FUNC
    );
    static final FunctionDescriptor RpcCancelThread$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcCancelThread$MH = RuntimeHelper.downcallHandle(
        "RpcCancelThread",
        constants$731.RpcCancelThread$FUNC
    );
    static final FunctionDescriptor RpcCancelThreadEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RpcCancelThreadEx$MH = RuntimeHelper.downcallHandle(
        "RpcCancelThreadEx",
        constants$731.RpcCancelThreadEx$FUNC
    );
    static final FunctionDescriptor UuidCreate$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidCreate$MH = RuntimeHelper.downcallHandle(
        "UuidCreate",
        constants$731.UuidCreate$FUNC
    );
    static final FunctionDescriptor UuidCreateSequential$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidCreateSequential$MH = RuntimeHelper.downcallHandle(
        "UuidCreateSequential",
        constants$731.UuidCreateSequential$FUNC
    );
    static final FunctionDescriptor UuidToStringA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidToStringA$MH = RuntimeHelper.downcallHandle(
        "UuidToStringA",
        constants$731.UuidToStringA$FUNC
    );
}


