// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$576 {

    static final FunctionDescriptor DlgDirSelectComboBoxExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DlgDirSelectComboBoxExW$MH = RuntimeHelper.downcallHandle(
        "DlgDirSelectComboBoxExW",
        constants$576.DlgDirSelectComboBoxExW$FUNC
    );
    static final FunctionDescriptor SetScrollInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetScrollInfo$MH = RuntimeHelper.downcallHandle(
        "SetScrollInfo",
        constants$576.SetScrollInfo$FUNC
    );
    static final FunctionDescriptor GetScrollInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetScrollInfo$MH = RuntimeHelper.downcallHandle(
        "GetScrollInfo",
        constants$576.GetScrollInfo$FUNC
    );
    static final FunctionDescriptor DefFrameProcA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DefFrameProcA$MH = RuntimeHelper.downcallHandle(
        "DefFrameProcA",
        constants$576.DefFrameProcA$FUNC
    );
    static final FunctionDescriptor DefFrameProcW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DefFrameProcW$MH = RuntimeHelper.downcallHandle(
        "DefFrameProcW",
        constants$576.DefFrameProcW$FUNC
    );
    static final FunctionDescriptor DefMDIChildProcA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DefMDIChildProcA$MH = RuntimeHelper.downcallHandle(
        "DefMDIChildProcA",
        constants$576.DefMDIChildProcA$FUNC
    );
}


