// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$202 {

    static final FunctionDescriptor GetDriveTypeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDriveTypeW$MH = RuntimeHelper.downcallHandle(
        "GetDriveTypeW",
        constants$202.GetDriveTypeW$FUNC
    );
    static final FunctionDescriptor GetFileAttributesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesA$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesA",
        constants$202.GetFileAttributesA$FUNC
    );
    static final FunctionDescriptor GetFileAttributesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesW$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesW",
        constants$202.GetFileAttributesW$FUNC
    );
    static final FunctionDescriptor GetFileAttributesExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesExA$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesExA",
        constants$202.GetFileAttributesExA$FUNC
    );
    static final FunctionDescriptor GetFileAttributesExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesExW$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesExW",
        constants$202.GetFileAttributesExW$FUNC
    );
    static final FunctionDescriptor GetFileInformationByHandle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileInformationByHandle$MH = RuntimeHelper.downcallHandle(
        "GetFileInformationByHandle",
        constants$202.GetFileInformationByHandle$FUNC
    );
}


