// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$305 {

    static final FunctionDescriptor GetSidSubAuthorityCount$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetSidSubAuthorityCount$MH = RuntimeHelper.downcallHandle(
        "GetSidSubAuthorityCount",
        constants$305.GetSidSubAuthorityCount$FUNC
    );
    static final FunctionDescriptor GetTokenInformation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetTokenInformation$MH = RuntimeHelper.downcallHandle(
        "GetTokenInformation",
        constants$305.GetTokenInformation$FUNC
    );
    static final FunctionDescriptor GetWindowsAccountDomainSid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowsAccountDomainSid$MH = RuntimeHelper.downcallHandle(
        "GetWindowsAccountDomainSid",
        constants$305.GetWindowsAccountDomainSid$FUNC
    );
    static final FunctionDescriptor ImpersonateAnonymousToken$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImpersonateAnonymousToken$MH = RuntimeHelper.downcallHandle(
        "ImpersonateAnonymousToken",
        constants$305.ImpersonateAnonymousToken$FUNC
    );
    static final FunctionDescriptor ImpersonateLoggedOnUser$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImpersonateLoggedOnUser$MH = RuntimeHelper.downcallHandle(
        "ImpersonateLoggedOnUser",
        constants$305.ImpersonateLoggedOnUser$FUNC
    );
    static final FunctionDescriptor ImpersonateSelf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ImpersonateSelf$MH = RuntimeHelper.downcallHandle(
        "ImpersonateSelf",
        constants$305.ImpersonateSelf$FUNC
    );
}


