// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$102 {

    static final FunctionDescriptor _stricmp_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _stricmp_l$MH = RuntimeHelper.downcallHandle(
        "_stricmp_l",
        constants$102._stricmp_l$FUNC
    );
    static final FunctionDescriptor strlen$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle strlen$MH = RuntimeHelper.downcallHandle(
        "strlen",
        constants$102.strlen$FUNC
    );
    static final FunctionDescriptor _strlwr_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _strlwr_s$MH = RuntimeHelper.downcallHandle(
        "_strlwr_s",
        constants$102._strlwr_s$FUNC
    );
    static final FunctionDescriptor _strlwr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _strlwr$MH = RuntimeHelper.downcallHandle(
        "_strlwr",
        constants$102._strlwr$FUNC
    );
    static final FunctionDescriptor _strlwr_s_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _strlwr_s_l$MH = RuntimeHelper.downcallHandle(
        "_strlwr_s_l",
        constants$102._strlwr_s_l$FUNC
    );
    static final FunctionDescriptor _strlwr_l$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _strlwr_l$MH = RuntimeHelper.downcallHandle(
        "_strlwr_l",
        constants$102._strlwr_l$FUNC
    );
}


