// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$454 {

    static final FunctionDescriptor SetMiterLimit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetMiterLimit$MH = RuntimeHelper.downcallHandle(
        "SetMiterLimit",
        constants$454.SetMiterLimit$FUNC
    );
    static final FunctionDescriptor StrokeAndFillPath$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle StrokeAndFillPath$MH = RuntimeHelper.downcallHandle(
        "StrokeAndFillPath",
        constants$454.StrokeAndFillPath$FUNC
    );
    static final FunctionDescriptor StrokePath$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle StrokePath$MH = RuntimeHelper.downcallHandle(
        "StrokePath",
        constants$454.StrokePath$FUNC
    );
    static final FunctionDescriptor WidenPath$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WidenPath$MH = RuntimeHelper.downcallHandle(
        "WidenPath",
        constants$454.WidenPath$FUNC
    );
    static final FunctionDescriptor ExtCreatePen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtCreatePen$MH = RuntimeHelper.downcallHandle(
        "ExtCreatePen",
        constants$454.ExtCreatePen$FUNC
    );
    static final FunctionDescriptor GetMiterLimit$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetMiterLimit$MH = RuntimeHelper.downcallHandle(
        "GetMiterLimit",
        constants$454.GetMiterLimit$FUNC
    );
}


