// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$588 {

    static final FunctionDescriptor GetThreadDpiHostingBehavior$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle GetThreadDpiHostingBehavior$MH = RuntimeHelper.downcallHandle(
        "GetThreadDpiHostingBehavior",
        constants$588.GetThreadDpiHostingBehavior$FUNC
    );
    static final FunctionDescriptor GetWindowDpiHostingBehavior$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowDpiHostingBehavior$MH = RuntimeHelper.downcallHandle(
        "GetWindowDpiHostingBehavior",
        constants$588.GetWindowDpiHostingBehavior$FUNC
    );
    static final FunctionDescriptor GetWindowModuleFileNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetWindowModuleFileNameA$MH = RuntimeHelper.downcallHandle(
        "GetWindowModuleFileNameA",
        constants$588.GetWindowModuleFileNameA$FUNC
    );
    static final FunctionDescriptor GetWindowModuleFileNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetWindowModuleFileNameW$MH = RuntimeHelper.downcallHandle(
        "GetWindowModuleFileNameW",
        constants$588.GetWindowModuleFileNameW$FUNC
    );
    static final FunctionDescriptor GetCursorInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCursorInfo$MH = RuntimeHelper.downcallHandle(
        "GetCursorInfo",
        constants$588.GetCursorInfo$FUNC
    );
    static final FunctionDescriptor GetWindowInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowInfo$MH = RuntimeHelper.downcallHandle(
        "GetWindowInfo",
        constants$588.GetWindowInfo$FUNC
    );
}


