// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$640 {

    static final FunctionDescriptor GetConsoleAliasExesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetConsoleAliasExesW$MH = RuntimeHelper.downcallHandle(
        "GetConsoleAliasExesW",
        constants$640.GetConsoleAliasExesW$FUNC
    );
    static final FunctionDescriptor ExpungeConsoleCommandHistoryA$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExpungeConsoleCommandHistoryA$MH = RuntimeHelper.downcallHandle(
        "ExpungeConsoleCommandHistoryA",
        constants$640.ExpungeConsoleCommandHistoryA$FUNC
    );
    static final FunctionDescriptor ExpungeConsoleCommandHistoryW$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExpungeConsoleCommandHistoryW$MH = RuntimeHelper.downcallHandle(
        "ExpungeConsoleCommandHistoryW",
        constants$640.ExpungeConsoleCommandHistoryW$FUNC
    );
    static final FunctionDescriptor SetConsoleNumberOfCommandsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleNumberOfCommandsA$MH = RuntimeHelper.downcallHandle(
        "SetConsoleNumberOfCommandsA",
        constants$640.SetConsoleNumberOfCommandsA$FUNC
    );
    static final FunctionDescriptor SetConsoleNumberOfCommandsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetConsoleNumberOfCommandsW$MH = RuntimeHelper.downcallHandle(
        "SetConsoleNumberOfCommandsW",
        constants$640.SetConsoleNumberOfCommandsW$FUNC
    );
    static final FunctionDescriptor GetConsoleCommandHistoryLengthA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetConsoleCommandHistoryLengthA$MH = RuntimeHelper.downcallHandle(
        "GetConsoleCommandHistoryLengthA",
        constants$640.GetConsoleCommandHistoryLengthA$FUNC
    );
}


