// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1155 {

    static final FunctionDescriptor CoRevokeInitializeSpy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("$anon$0"),
            MemoryLayout.structLayout(
                Constants$root.C_LONG$LAYOUT.withName("LowPart"),
                Constants$root.C_LONG$LAYOUT.withName("HighPart")
            ).withName("u"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("QuadPart")
        ).withName("_ULARGE_INTEGER")
    );
    static final MethodHandle CoRevokeInitializeSpy$MH = RuntimeHelper.downcallHandle(
        "CoRevokeInitializeSpy",
        constants$1155.CoRevokeInitializeSpy$FUNC
    );
    static final FunctionDescriptor CoGetSystemSecurityPermissions$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetSystemSecurityPermissions$MH = RuntimeHelper.downcallHandle(
        "CoGetSystemSecurityPermissions",
        constants$1155.CoGetSystemSecurityPermissions$FUNC
    );
    static final FunctionDescriptor CoLoadLibrary$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CoLoadLibrary$MH = RuntimeHelper.downcallHandle(
        "CoLoadLibrary",
        constants$1155.CoLoadLibrary$FUNC
    );
    static final FunctionDescriptor CoFreeLibrary$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoFreeLibrary$MH = RuntimeHelper.downcallHandle(
        "CoFreeLibrary",
        constants$1155.CoFreeLibrary$FUNC
    );
    static final FunctionDescriptor CoFreeAllLibraries$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle CoFreeAllLibraries$MH = RuntimeHelper.downcallHandle(
        "CoFreeAllLibraries",
        constants$1155.CoFreeAllLibraries$FUNC
    );
    static final FunctionDescriptor CoGetInstanceFromFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetInstanceFromFile$MH = RuntimeHelper.downcallHandle(
        "CoGetInstanceFromFile",
        constants$1155.CoGetInstanceFromFile$FUNC
    );
}


