// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$186 {

    static final FunctionDescriptor PTP_SIMPLE_CALLBACK$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PTP_SIMPLE_CALLBACK$MH = RuntimeHelper.downcallHandle(
        constants$186.PTP_SIMPLE_CALLBACK$FUNC
    );
    static final FunctionDescriptor PTP_CLEANUP_GROUP_CANCEL_CALLBACK$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PTP_CLEANUP_GROUP_CANCEL_CALLBACK$MH = RuntimeHelper.downcallHandle(
        constants$186.PTP_CLEANUP_GROUP_CANCEL_CALLBACK$FUNC
    );
    static final FunctionDescriptor TpInitializeCallbackEnviron$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle TpInitializeCallbackEnviron$MH = RuntimeHelper.downcallHandle(
        "TpInitializeCallbackEnviron",
        constants$186.TpInitializeCallbackEnviron$FUNC
    );
    static final FunctionDescriptor TpSetCallbackThreadpool$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle TpSetCallbackThreadpool$MH = RuntimeHelper.downcallHandle(
        "TpSetCallbackThreadpool",
        constants$186.TpSetCallbackThreadpool$FUNC
    );
    static final FunctionDescriptor TpSetCallbackCleanupGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle TpSetCallbackCleanupGroup$MH = RuntimeHelper.downcallHandle(
        "TpSetCallbackCleanupGroup",
        constants$186.TpSetCallbackCleanupGroup$FUNC
    );
}


