// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$526 {

    static final FunctionDescriptor PackTouchHitTestingProximityEvaluation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PackTouchHitTestingProximityEvaluation$MH = RuntimeHelper.downcallHandle(
        "PackTouchHitTestingProximityEvaluation",
        constants$526.PackTouchHitTestingProximityEvaluation$FUNC
    );
    static final FunctionDescriptor GetWindowFeedbackSetting$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowFeedbackSetting$MH = RuntimeHelper.downcallHandle(
        "GetWindowFeedbackSetting",
        constants$526.GetWindowFeedbackSetting$FUNC
    );
    static final FunctionDescriptor SetWindowFeedbackSetting$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetWindowFeedbackSetting$MH = RuntimeHelper.downcallHandle(
        "SetWindowFeedbackSetting",
        constants$526.SetWindowFeedbackSetting$FUNC
    );
    static final FunctionDescriptor GetPointerInputTransform$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPointerInputTransform$MH = RuntimeHelper.downcallHandle(
        "GetPointerInputTransform",
        constants$526.GetPointerInputTransform$FUNC
    );
    static final FunctionDescriptor GetLastInputInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetLastInputInfo$MH = RuntimeHelper.downcallHandle(
        "GetLastInputInfo",
        constants$526.GetLastInputInfo$FUNC
    );
    static final FunctionDescriptor MapVirtualKeyA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle MapVirtualKeyA$MH = RuntimeHelper.downcallHandle(
        "MapVirtualKeyA",
        constants$526.MapVirtualKeyA$FUNC
    );
}


