// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1399 {

    static final FunctionDescriptor curl_easy_send$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_easy_send$MH = RuntimeHelper.downcallHandle(
        "curl_easy_send",
        constants$1399.curl_easy_send$FUNC
    );
    static final FunctionDescriptor curl_easy_upkeep$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_easy_upkeep$MH = RuntimeHelper.downcallHandle(
        "curl_easy_upkeep",
        constants$1399.curl_easy_upkeep$FUNC
    );
    static final FunctionDescriptor curl_multi_init$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle curl_multi_init$MH = RuntimeHelper.downcallHandle(
        "curl_multi_init",
        constants$1399.curl_multi_init$FUNC
    );
    static final FunctionDescriptor curl_multi_add_handle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_multi_add_handle$MH = RuntimeHelper.downcallHandle(
        "curl_multi_add_handle",
        constants$1399.curl_multi_add_handle$FUNC
    );
    static final FunctionDescriptor curl_multi_remove_handle$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_multi_remove_handle$MH = RuntimeHelper.downcallHandle(
        "curl_multi_remove_handle",
        constants$1399.curl_multi_remove_handle$FUNC
    );
    static final FunctionDescriptor curl_multi_fdset$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle curl_multi_fdset$MH = RuntimeHelper.downcallHandle(
        "curl_multi_fdset",
        constants$1399.curl_multi_fdset$FUNC
    );
}


