// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$748 {

    static final FunctionDescriptor I_RpcBindingInqConnId$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingInqConnId$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingInqConnId",
        constants$748.I_RpcBindingInqConnId$FUNC
    );
    static final FunctionDescriptor I_RpcBindingCreateNP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingCreateNP$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingCreateNP",
        constants$748.I_RpcBindingCreateNP$FUNC
    );
    static final FunctionDescriptor I_RpcSsDontSerializeContext$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle I_RpcSsDontSerializeContext$MH = RuntimeHelper.downcallHandle(
        "I_RpcSsDontSerializeContext",
        constants$748.I_RpcSsDontSerializeContext$FUNC
    );
    static final FunctionDescriptor I_RpcLaunchDatagramReceiveThread$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcLaunchDatagramReceiveThread$MH = RuntimeHelper.downcallHandle(
        "I_RpcLaunchDatagramReceiveThread",
        constants$748.I_RpcLaunchDatagramReceiveThread$FUNC
    );
    static final FunctionDescriptor I_RpcServerRegisterForwardFunction$pForwardFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcServerRegisterForwardFunction$pForwardFunction$MH = RuntimeHelper.downcallHandle(
        constants$748.I_RpcServerRegisterForwardFunction$pForwardFunction$FUNC
    );
}


