// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$112 {

    static final FunctionDescriptor _BitScanReverse64$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _BitScanReverse64$MH = RuntimeHelper.downcallHandle(
        "_BitScanReverse64",
        constants$112._BitScanReverse64$FUNC
    );
    static final FunctionDescriptor _InterlockedIncrement16$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _InterlockedIncrement16$MH = RuntimeHelper.downcallHandle(
        "_InterlockedIncrement16",
        constants$112._InterlockedIncrement16$FUNC
    );
    static final FunctionDescriptor _InterlockedDecrement16$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _InterlockedDecrement16$MH = RuntimeHelper.downcallHandle(
        "_InterlockedDecrement16",
        constants$112._InterlockedDecrement16$FUNC
    );
    static final FunctionDescriptor _InterlockedCompareExchange16$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle _InterlockedCompareExchange16$MH = RuntimeHelper.downcallHandle(
        "_InterlockedCompareExchange16",
        constants$112._InterlockedCompareExchange16$FUNC
    );
    static final FunctionDescriptor _InterlockedAnd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _InterlockedAnd$MH = RuntimeHelper.downcallHandle(
        "_InterlockedAnd",
        constants$112._InterlockedAnd$FUNC
    );
    static final FunctionDescriptor _InterlockedOr$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _InterlockedOr$MH = RuntimeHelper.downcallHandle(
        "_InterlockedOr",
        constants$112._InterlockedOr$FUNC
    );
}


