// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$75 {

    static final FunctionDescriptor _ispunct_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _ispunct_l$MH = RuntimeHelper.downcallHandle(
        "_ispunct_l",
        constants$75._ispunct_l$FUNC
    );
    static final FunctionDescriptor isblank$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle isblank$MH = RuntimeHelper.downcallHandle(
        "isblank",
        constants$75.isblank$FUNC
    );
    static final FunctionDescriptor _isblank_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _isblank_l$MH = RuntimeHelper.downcallHandle(
        "_isblank_l",
        constants$75._isblank_l$FUNC
    );
    static final FunctionDescriptor isalnum$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle isalnum$MH = RuntimeHelper.downcallHandle(
        "isalnum",
        constants$75.isalnum$FUNC
    );
    static final FunctionDescriptor _isalnum_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _isalnum_l$MH = RuntimeHelper.downcallHandle(
        "_isalnum_l",
        constants$75._isalnum_l$FUNC
    );
    static final FunctionDescriptor isprint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle isprint$MH = RuntimeHelper.downcallHandle(
        "isprint",
        constants$75.isprint$FUNC
    );
}


