// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$803 {

    static final FunctionDescriptor PFN_NCRYPT_FREE$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_NCRYPT_FREE$MH = RuntimeHelper.downcallHandle(
        constants$803.PFN_NCRYPT_FREE$FUNC
    );
    static final FunctionDescriptor NCryptOpenStorageProvider$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NCryptOpenStorageProvider$MH = RuntimeHelper.downcallHandle(
        "NCryptOpenStorageProvider",
        constants$803.NCryptOpenStorageProvider$FUNC
    );
    static final FunctionDescriptor NCryptEnumAlgorithms$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NCryptEnumAlgorithms$MH = RuntimeHelper.downcallHandle(
        "NCryptEnumAlgorithms",
        constants$803.NCryptEnumAlgorithms$FUNC
    );
    static final FunctionDescriptor NCryptIsAlgSupported$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NCryptIsAlgSupported$MH = RuntimeHelper.downcallHandle(
        "NCryptIsAlgSupported",
        constants$803.NCryptIsAlgSupported$FUNC
    );
    static final FunctionDescriptor NCryptEnumKeys$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle NCryptEnumKeys$MH = RuntimeHelper.downcallHandle(
        "NCryptEnumKeys",
        constants$803.NCryptEnumKeys$FUNC
    );
}


