// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$429 {

    static final FunctionDescriptor GetCharacterPlacementW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCharacterPlacementW$MH = RuntimeHelper.downcallHandle(
        "GetCharacterPlacementW",
        constants$429.GetCharacterPlacementW$FUNC
    );
    static final FunctionDescriptor GetFontUnicodeRanges$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFontUnicodeRanges$MH = RuntimeHelper.downcallHandle(
        "GetFontUnicodeRanges",
        constants$429.GetFontUnicodeRanges$FUNC
    );
    static final FunctionDescriptor GetGlyphIndicesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetGlyphIndicesA$MH = RuntimeHelper.downcallHandle(
        "GetGlyphIndicesA",
        constants$429.GetGlyphIndicesA$FUNC
    );
    static final FunctionDescriptor GetGlyphIndicesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetGlyphIndicesW$MH = RuntimeHelper.downcallHandle(
        "GetGlyphIndicesW",
        constants$429.GetGlyphIndicesW$FUNC
    );
    static final FunctionDescriptor GetTextExtentPointI$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetTextExtentPointI$MH = RuntimeHelper.downcallHandle(
        "GetTextExtentPointI",
        constants$429.GetTextExtentPointI$FUNC
    );
    static final FunctionDescriptor GetTextExtentExPointI$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetTextExtentExPointI$MH = RuntimeHelper.downcallHandle(
        "GetTextExtentExPointI",
        constants$429.GetTextExtentExPointI$FUNC
    );
}


