// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$213 {

    static final FunctionDescriptor DeleteFileFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeleteFileFromAppW$MH = RuntimeHelper.downcallHandle(
        "DeleteFileFromAppW",
        constants$213.DeleteFileFromAppW$FUNC
    );
    static final FunctionDescriptor FindFirstFileExFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle FindFirstFileExFromAppW$MH = RuntimeHelper.downcallHandle(
        "FindFirstFileExFromAppW",
        constants$213.FindFirstFileExFromAppW$FUNC
    );
    static final FunctionDescriptor GetFileAttributesExFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesExFromAppW$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesExFromAppW",
        constants$213.GetFileAttributesExFromAppW$FUNC
    );
    static final FunctionDescriptor MoveFileFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MoveFileFromAppW$MH = RuntimeHelper.downcallHandle(
        "MoveFileFromAppW",
        constants$213.MoveFileFromAppW$FUNC
    );
    static final FunctionDescriptor RemoveDirectoryFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveDirectoryFromAppW$MH = RuntimeHelper.downcallHandle(
        "RemoveDirectoryFromAppW",
        constants$213.RemoveDirectoryFromAppW$FUNC
    );
    static final FunctionDescriptor ReplaceFileFromAppW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReplaceFileFromAppW$MH = RuntimeHelper.downcallHandle(
        "ReplaceFileFromAppW",
        constants$213.ReplaceFileFromAppW$FUNC
    );
}


