// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$656 {

    static final FunctionDescriptor RegDeleteKeyValueA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegDeleteKeyValueA$MH = RuntimeHelper.downcallHandle(
        "RegDeleteKeyValueA",
        constants$656.RegDeleteKeyValueA$FUNC
    );
    static final FunctionDescriptor RegDeleteKeyValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegDeleteKeyValueW$MH = RuntimeHelper.downcallHandle(
        "RegDeleteKeyValueW",
        constants$656.RegDeleteKeyValueW$FUNC
    );
    static final FunctionDescriptor RegSetKeyValueA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegSetKeyValueA$MH = RuntimeHelper.downcallHandle(
        "RegSetKeyValueA",
        constants$656.RegSetKeyValueA$FUNC
    );
    static final FunctionDescriptor RegSetKeyValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle RegSetKeyValueW$MH = RuntimeHelper.downcallHandle(
        "RegSetKeyValueW",
        constants$656.RegSetKeyValueW$FUNC
    );
    static final FunctionDescriptor RegDeleteTreeA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegDeleteTreeA$MH = RuntimeHelper.downcallHandle(
        "RegDeleteTreeA",
        constants$656.RegDeleteTreeA$FUNC
    );
    static final FunctionDescriptor RegDeleteTreeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegDeleteTreeW$MH = RuntimeHelper.downcallHandle(
        "RegDeleteTreeW",
        constants$656.RegDeleteTreeW$FUNC
    );
}


