// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$801 {

    static final FunctionDescriptor BCryptConfigureContextFunction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptConfigureContextFunction$MH = RuntimeHelper.downcallHandle(
        "BCryptConfigureContextFunction",
        constants$801.BCryptConfigureContextFunction$FUNC
    );
    static final FunctionDescriptor BCryptQueryContextFunctionConfiguration$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptQueryContextFunctionConfiguration$MH = RuntimeHelper.downcallHandle(
        "BCryptQueryContextFunctionConfiguration",
        constants$801.BCryptQueryContextFunctionConfiguration$FUNC
    );
    static final FunctionDescriptor BCryptEnumContextFunctionProviders$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptEnumContextFunctionProviders$MH = RuntimeHelper.downcallHandle(
        "BCryptEnumContextFunctionProviders",
        constants$801.BCryptEnumContextFunctionProviders$FUNC
    );
    static final FunctionDescriptor BCryptSetContextFunctionProperty$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptSetContextFunctionProperty$MH = RuntimeHelper.downcallHandle(
        "BCryptSetContextFunctionProperty",
        constants$801.BCryptSetContextFunctionProperty$FUNC
    );
    static final FunctionDescriptor BCryptQueryContextFunctionProperty$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptQueryContextFunctionProperty$MH = RuntimeHelper.downcallHandle(
        "BCryptQueryContextFunctionProperty",
        constants$801.BCryptQueryContextFunctionProperty$FUNC
    );
    static final FunctionDescriptor BCryptRegisterConfigChangeNotify$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptRegisterConfigChangeNotify$MH = RuntimeHelper.downcallHandle(
        "BCryptRegisterConfigChangeNotify",
        constants$801.BCryptRegisterConfigChangeNotify$FUNC
    );
}


