// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$938 {

    static final FunctionDescriptor SCardCancel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SCardCancel$MH = RuntimeHelper.downcallHandle(
        "SCardCancel",
        constants$938.SCardCancel$FUNC
    );
    static final FunctionDescriptor SCardConnectA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardConnectA$MH = RuntimeHelper.downcallHandle(
        "SCardConnectA",
        constants$938.SCardConnectA$FUNC
    );
    static final FunctionDescriptor SCardConnectW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardConnectW$MH = RuntimeHelper.downcallHandle(
        "SCardConnectW",
        constants$938.SCardConnectW$FUNC
    );
    static final FunctionDescriptor SCardReconnect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardReconnect$MH = RuntimeHelper.downcallHandle(
        "SCardReconnect",
        constants$938.SCardReconnect$FUNC
    );
    static final FunctionDescriptor SCardDisconnect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardDisconnect$MH = RuntimeHelper.downcallHandle(
        "SCardDisconnect",
        constants$938.SCardDisconnect$FUNC
    );
    static final FunctionDescriptor SCardBeginTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SCardBeginTransaction$MH = RuntimeHelper.downcallHandle(
        "SCardBeginTransaction",
        constants$938.SCardBeginTransaction$FUNC
    );
}


