// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$261 {

    static final FunctionDescriptor GetSystemFirmwareTable$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetSystemFirmwareTable$MH = RuntimeHelper.downcallHandle(
        "GetSystemFirmwareTable",
        constants$261.GetSystemFirmwareTable$FUNC
    );
    static final FunctionDescriptor DnsHostnameToComputerNameExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DnsHostnameToComputerNameExW$MH = RuntimeHelper.downcallHandle(
        "DnsHostnameToComputerNameExW",
        constants$261.DnsHostnameToComputerNameExW$FUNC
    );
    static final FunctionDescriptor GetPhysicallyInstalledSystemMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPhysicallyInstalledSystemMemory$MH = RuntimeHelper.downcallHandle(
        "GetPhysicallyInstalledSystemMemory",
        constants$261.GetPhysicallyInstalledSystemMemory$FUNC
    );
    static final FunctionDescriptor SetComputerNameEx2W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetComputerNameEx2W$MH = RuntimeHelper.downcallHandle(
        "SetComputerNameEx2W",
        constants$261.SetComputerNameEx2W$FUNC
    );
    static final FunctionDescriptor SetSystemTimeAdjustment$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetSystemTimeAdjustment$MH = RuntimeHelper.downcallHandle(
        "SetSystemTimeAdjustment",
        constants$261.SetSystemTimeAdjustment$FUNC
    );
    static final FunctionDescriptor SetSystemTimeAdjustmentPrecise$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetSystemTimeAdjustmentPrecise$MH = RuntimeHelper.downcallHandle(
        "SetSystemTimeAdjustmentPrecise",
        constants$261.SetSystemTimeAdjustmentPrecise$FUNC
    );
}


