// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$982 {

    static final FunctionDescriptor wcstoll$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wcstoll$MH = RuntimeHelper.downcallHandle(
        "wcstoll",
        constants$982.wcstoll$FUNC
    );
    static final FunctionDescriptor _wcstoll_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoll_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoll_l",
        constants$982._wcstoll_l$FUNC
    );
    static final FunctionDescriptor wcstoul$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wcstoul$MH = RuntimeHelper.downcallHandle(
        "wcstoul",
        constants$982.wcstoul$FUNC
    );
    static final FunctionDescriptor _wcstoul_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoul_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoul_l",
        constants$982._wcstoul_l$FUNC
    );
    static final FunctionDescriptor wcstoull$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle wcstoull$MH = RuntimeHelper.downcallHandle(
        "wcstoull",
        constants$982.wcstoull$FUNC
    );
    static final FunctionDescriptor _wcstoull_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstoull_l$MH = RuntimeHelper.downcallHandle(
        "_wcstoull_l",
        constants$982._wcstoull_l$FUNC
    );
}


