// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$521 {

    static final FunctionDescriptor InitializeTouchInjection$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle InitializeTouchInjection$MH = RuntimeHelper.downcallHandle(
        "InitializeTouchInjection",
        constants$521.InitializeTouchInjection$FUNC
    );
    static final FunctionDescriptor InjectTouchInput$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle InjectTouchInput$MH = RuntimeHelper.downcallHandle(
        "InjectTouchInput",
        constants$521.InjectTouchInput$FUNC
    );
    static final FunctionDescriptor GetPointerType$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPointerType$MH = RuntimeHelper.downcallHandle(
        "GetPointerType",
        constants$521.GetPointerType$FUNC
    );
    static final FunctionDescriptor GetPointerCursorId$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPointerCursorId$MH = RuntimeHelper.downcallHandle(
        "GetPointerCursorId",
        constants$521.GetPointerCursorId$FUNC
    );
    static final FunctionDescriptor GetPointerInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPointerInfo$MH = RuntimeHelper.downcallHandle(
        "GetPointerInfo",
        constants$521.GetPointerInfo$FUNC
    );
    static final FunctionDescriptor GetPointerInfoHistory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPointerInfoHistory$MH = RuntimeHelper.downcallHandle(
        "GetPointerInfoHistory",
        constants$521.GetPointerInfoHistory$FUNC
    );
}


