// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$550 {

    static final FunctionDescriptor GetWindowTextA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetWindowTextA$MH = RuntimeHelper.downcallHandle(
        "GetWindowTextA",
        constants$550.GetWindowTextA$FUNC
    );
    static final FunctionDescriptor GetWindowTextW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetWindowTextW$MH = RuntimeHelper.downcallHandle(
        "GetWindowTextW",
        constants$550.GetWindowTextW$FUNC
    );
    static final FunctionDescriptor GetWindowTextLengthA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowTextLengthA$MH = RuntimeHelper.downcallHandle(
        "GetWindowTextLengthA",
        constants$550.GetWindowTextLengthA$FUNC
    );
    static final FunctionDescriptor GetWindowTextLengthW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowTextLengthW$MH = RuntimeHelper.downcallHandle(
        "GetWindowTextLengthW",
        constants$550.GetWindowTextLengthW$FUNC
    );
    static final FunctionDescriptor GetClientRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetClientRect$MH = RuntimeHelper.downcallHandle(
        "GetClientRect",
        constants$550.GetClientRect$FUNC
    );
    static final FunctionDescriptor GetWindowRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetWindowRect$MH = RuntimeHelper.downcallHandle(
        "GetWindowRect",
        constants$550.GetWindowRect$FUNC
    );
}


