// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$685 {

    static final FunctionDescriptor mmioRenameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRenameA$MH = RuntimeHelper.downcallHandle(
        "mmioRenameA",
        constants$685.mmioRenameA$FUNC
    );
    static final FunctionDescriptor mmioRenameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRenameW$MH = RuntimeHelper.downcallHandle(
        "mmioRenameW",
        constants$685.mmioRenameW$FUNC
    );
    static final FunctionDescriptor mmioClose$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioClose$MH = RuntimeHelper.downcallHandle(
        "mmioClose",
        constants$685.mmioClose$FUNC
    );
    static final FunctionDescriptor mmioRead$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioRead$MH = RuntimeHelper.downcallHandle(
        "mmioRead",
        constants$685.mmioRead$FUNC
    );
    static final FunctionDescriptor mmioWrite$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioWrite$MH = RuntimeHelper.downcallHandle(
        "mmioWrite",
        constants$685.mmioWrite$FUNC
    );
    static final FunctionDescriptor mmioSeek$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle mmioSeek$MH = RuntimeHelper.downcallHandle(
        "mmioSeek",
        constants$685.mmioSeek$FUNC
    );
}


