// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$718 {

    static final FunctionDescriptor RpcServerRegisterIfEx$IfCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerRegisterIfEx$IfCallback$MH = RuntimeHelper.downcallHandle(
        constants$718.RpcServerRegisterIfEx$IfCallback$FUNC
    );
    static final FunctionDescriptor RpcServerRegisterIfEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerRegisterIfEx$MH = RuntimeHelper.downcallHandle(
        "RpcServerRegisterIfEx",
        constants$718.RpcServerRegisterIfEx$FUNC
    );
    static final FunctionDescriptor RpcServerRegisterIf2$IfCallbackFn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerRegisterIf2$IfCallbackFn$MH = RuntimeHelper.downcallHandle(
        constants$718.RpcServerRegisterIf2$IfCallbackFn$FUNC
    );
    static final FunctionDescriptor RpcServerRegisterIf2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerRegisterIf2$MH = RuntimeHelper.downcallHandle(
        "RpcServerRegisterIf2",
        constants$718.RpcServerRegisterIf2$FUNC
    );
    static final FunctionDescriptor RpcServerRegisterIf3$IfCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


