// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$756 {

    static final FunctionDescriptor I_RpcProxyUpdatePerfCounterBackendServerFn$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle I_RpcProxyUpdatePerfCounterBackendServerFn$MH = RuntimeHelper.downcallHandle(
        constants$756.I_RpcProxyUpdatePerfCounterBackendServerFn$FUNC
    );
    static final FunctionDescriptor I_RpcProxyNewConnection$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcProxyNewConnection$MH = RuntimeHelper.downcallHandle(
        "I_RpcProxyNewConnection",
        constants$756.I_RpcProxyNewConnection$FUNC
    );
    static final FunctionDescriptor I_RpcReplyToClientWithStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle I_RpcReplyToClientWithStatus$MH = RuntimeHelper.downcallHandle(
        "I_RpcReplyToClientWithStatus",
        constants$756.I_RpcReplyToClientWithStatus$FUNC
    );
    static final FunctionDescriptor I_RpcRecordCalloutFailure$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcRecordCalloutFailure$MH = RuntimeHelper.downcallHandle(
        "I_RpcRecordCalloutFailure",
        constants$756.I_RpcRecordCalloutFailure$FUNC
    );
    static final FunctionDescriptor I_RpcMgmtEnableDedicatedThreadPool$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle I_RpcMgmtEnableDedicatedThreadPool$MH = RuntimeHelper.downcallHandle(
        "I_RpcMgmtEnableDedicatedThreadPool",
        constants$756.I_RpcMgmtEnableDedicatedThreadPool$FUNC
    );
}


