// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$134 {

    static final FunctionDescriptor ReadUShortRaw$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReadUShortRaw$MH = RuntimeHelper.downcallHandle(
        "ReadUShortRaw",
        constants$134.ReadUShortRaw$FUNC
    );
    static final FunctionDescriptor WriteUShortRelease$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle WriteUShortRelease$MH = RuntimeHelper.downcallHandle(
        "WriteUShortRelease",
        constants$134.WriteUShortRelease$FUNC
    );
    static final FunctionDescriptor WriteUShortNoFence$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle WriteUShortNoFence$MH = RuntimeHelper.downcallHandle(
        "WriteUShortNoFence",
        constants$134.WriteUShortNoFence$FUNC
    );
    static final FunctionDescriptor WriteUShortRaw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle WriteUShortRaw$MH = RuntimeHelper.downcallHandle(
        "WriteUShortRaw",
        constants$134.WriteUShortRaw$FUNC
    );
    static final FunctionDescriptor ReadULongAcquire$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReadULongAcquire$MH = RuntimeHelper.downcallHandle(
        "ReadULongAcquire",
        constants$134.ReadULongAcquire$FUNC
    );
    static final FunctionDescriptor ReadULongNoFence$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReadULongNoFence$MH = RuntimeHelper.downcallHandle(
        "ReadULongNoFence",
        constants$134.ReadULongNoFence$FUNC
    );
}


