// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$78 {

    static final FunctionDescriptor __toascii$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __toascii$MH = RuntimeHelper.downcallHandle(
        "__toascii",
        constants$78.__toascii$FUNC
    );
    static final FunctionDescriptor __iscsymf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __iscsymf$MH = RuntimeHelper.downcallHandle(
        "__iscsymf",
        constants$78.__iscsymf$FUNC
    );
    static final FunctionDescriptor __iscsym$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __iscsym$MH = RuntimeHelper.downcallHandle(
        "__iscsym",
        constants$78.__iscsym$FUNC
    );
    static final FunctionDescriptor __acrt_locale_get_ctype_array_value$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __acrt_locale_get_ctype_array_value$MH = RuntimeHelper.downcallHandle(
        "__acrt_locale_get_ctype_array_value",
        constants$78.__acrt_locale_get_ctype_array_value$FUNC
    );
    static final FunctionDescriptor ___mb_cur_max_func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle ___mb_cur_max_func$MH = RuntimeHelper.downcallHandle(
        "___mb_cur_max_func",
        constants$78.___mb_cur_max_func$FUNC
    );
    static final FunctionDescriptor ___mb_cur_max_l_func$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ___mb_cur_max_l_func$MH = RuntimeHelper.downcallHandle(
        "___mb_cur_max_l_func",
        constants$78.___mb_cur_max_l_func$FUNC
    );
}


