// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class curl_tlssessioninfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("backend"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("internals")
    ).withName("curl_tlssessioninfo");
    public static MemoryLayout $LAYOUT() {
        return curl_tlssessioninfo.$struct$LAYOUT;
    }
    static final VarHandle backend$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("backend"));
    public static VarHandle backend$VH() {
        return curl_tlssessioninfo.backend$VH;
    }
    public static int backend$get(MemorySegment seg) {
        return (int)curl_tlssessioninfo.backend$VH.get(seg);
    }
    public static void backend$set( MemorySegment seg, int x) {
        curl_tlssessioninfo.backend$VH.set(seg, x);
    }
    public static int backend$get(MemorySegment seg, long index) {
        return (int)curl_tlssessioninfo.backend$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void backend$set(MemorySegment seg, long index, int x) {
        curl_tlssessioninfo.backend$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle internals$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("internals"));
    public static VarHandle internals$VH() {
        return curl_tlssessioninfo.internals$VH;
    }
    public static MemoryAddress internals$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)curl_tlssessioninfo.internals$VH.get(seg);
    }
    public static void internals$set( MemorySegment seg, MemoryAddress x) {
        curl_tlssessioninfo.internals$VH.set(seg, x);
    }
    public static MemoryAddress internals$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)curl_tlssessioninfo.internals$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void internals$set(MemorySegment seg, long index, MemoryAddress x) {
        curl_tlssessioninfo.internals$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


