// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface curl_free_callback {

    void apply(java.lang.foreign.MemoryAddress ptr);
    static MemorySegment allocate(curl_free_callback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(curl_free_callback.class, fi, constants$1386.curl_free_callback$FUNC, session);
    }
    static curl_free_callback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _ptr) -> {
            try {
                constants$1386.curl_free_callback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_ptr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


