// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface curl_formget_callback {

    long apply(java.lang.foreign.MemoryAddress arg, java.lang.foreign.MemoryAddress buf, long len);
    static MemorySegment allocate(curl_formget_callback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(curl_formget_callback.class, fi, constants$1392.curl_formget_callback$FUNC, session);
    }
    static curl_formget_callback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _arg, java.lang.foreign.MemoryAddress _buf, long _len) -> {
            try {
                return (long)constants$1393.curl_formget_callback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_arg, (java.lang.foreign.Addressable)_buf, _len);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


