// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface curl_hstswrite_callback {

    int apply(java.lang.foreign.MemoryAddress easy, java.lang.foreign.MemoryAddress e, java.lang.foreign.MemoryAddress i, java.lang.foreign.MemoryAddress userp);
    static MemorySegment allocate(curl_hstswrite_callback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(curl_hstswrite_callback.class, fi, constants$1390.curl_hstswrite_callback$FUNC, session);
    }
    static curl_hstswrite_callback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _easy, java.lang.foreign.MemoryAddress _e, java.lang.foreign.MemoryAddress _i, java.lang.foreign.MemoryAddress _userp) -> {
            try {
                return (int)constants$1390.curl_hstswrite_callback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_easy, (java.lang.foreign.Addressable)_e, (java.lang.foreign.Addressable)_i, (java.lang.foreign.Addressable)_userp);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


