// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface curl_seek_callback {

    int apply(java.lang.foreign.MemoryAddress instream, long offset, int origin);
    static MemorySegment allocate(curl_seek_callback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(curl_seek_callback.class, fi, constants$1383.curl_seek_callback$FUNC, session);
    }
    static curl_seek_callback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _instream, long _offset, int _origin) -> {
            try {
                return (int)constants$1383.curl_seek_callback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_instream, _offset, _origin);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


