// Generated by jextract

package cn.smilex;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface RpcSsSwapClientAllocFree$ClientFree {

    void apply(java.lang.foreign.MemoryAddress _x0);
    static MemorySegment allocate(RpcSsSwapClientAllocFree$ClientFree fi, MemorySession session) {
        return RuntimeHelper.upcallStub(RpcSsSwapClientAllocFree$ClientFree.class, fi, constants$911.RpcSsSwapClientAllocFree$ClientFree$FUNC, session);
    }
    static RpcSsSwapClientAllocFree$ClientFree ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress __x0) -> {
            try {
                constants$911.RpcSsSwapClientAllocFree$ClientFree$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


